### ISSUE TITLE
[Forum]: Tack-funktion

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#10]
Skapa “Tack”-funktion för användning i bbPress. (En funktion som varit väldigt uppskattad av dom som hjälper till att svara på frågor i forumet där användaren enkelt kan klicka på en knapp och på så sätt säga tack för hjälpen).

Konceptet är väldigt enkelt. En knapp som kan klickas på av vem som helst för att tacka för ett inlägg som gjorts i forumet.

Skulle enkelt kunna göras med ett custom field och då helst som ett tillägg.

**Comment by EyesX** [comment]
Att tänka på när vi skapar funktionalitet som tillägg är att inte lägga med någon formatering, utan istället låta temat sköta den biten. På så sätt kan vi enkelt uppdatera temat utan att det kräver handpåläggning i tilläggen.

**Comment by jonathan-dejong** [comment]
Jag tycker att Elliots nya struktur på supporten på ACF har en ganska bra lösning.. Jag har för mig att det också är BBpress och så kör han med en progressmätare där du får en viss rank vid visst antal tack:
http://support.advancedcustomfields.com/

**Comment by EyesX** [comment]
Ser intressant ut. Men ser mer ut som det är en "markera som löst"-funktion va? Det är dock något vi behöver också #9 .

**Comment by jonathan-dejong** [comment]
Det är två i ett.. De kan välja vilket svar som hjälpt dem mest/helt och den personen som gjort det svaret får +1 till sin rank. Jag har t.ex. ca 55 poäng och har då förtjänat ranken ACF expert. vid 100 är man ACF Guru. 

Man kan köra en sån funktion men så klart lägga till flera ranker mellan 1-200 eller något och lägga till fler efterhand som det behövs.

**Comment by EyesX** [comment]
Det låter klart intressant. Vet du om det finns något klart tillägg som fixar detta eller behöver vi bygga ett eget?

**Comment by jonathan-dejong** [comment]
Jag ska höra med Elliot.. :)

**Comment by jonathan-dejong** [comment]
Jag har skickat iväg en fråga till honom så vi får se när han svarar! Sitter ju i Australien så det är lite annan tidszon ;)

**Comment by jonathan-dejong** [comment]
Nu har jag pratat med Elliot på ACF. 
Han har tydligen byggt funktionen själv via ACF fält.. Men när vi diskuterade det så verkar det faktiskt inte så komplicerat. 
Användarens ranksystem kan man enkelt skapa med ett numbers-fält på user profile som man håller gömd från användaren (om de ska ha tillgång till wp profile sidan). Sen kör vi väl bara in en funktion i functions (eller plugin) som räknar ut en rank beroende på deras siffra. På så sätt kan vi enkelt centralt skapa nya ranks etc. 

Tråd-progression (olöst, pågående, löst t.ex.) kan man fixa med en flerväljare i t.ex. ACF som också sätts automatiskt vid trådsvar och sedan när trådskaparen valt ett inlägg som en lösning sätts den till "löst". Sen får man fixa ett fält på alla inlägg i trådarna (typ true/false) som sätts till true när ett inlägg markeras som "lösning". På så sätt kan man styla till det annorlunda etc. 

Så all in all känns det inte som en så svår grej att fixa själv + att då får vi obegränsade möjligheter för vidareutveckling :)

Vad sägs?

**Comment by EyesX** [comment]
Det låter vettigt. Vi är nog kvar på ruta ett fortfarande då, men med lite idéer på hur vi går vidare.

Jag tror att vi ska skippar det här med rank, eller helt enkelt inte kallar det rank utan snarare kallar det uppskattningssystem (vi har inaktiverat det i alla tidigare versioner). Rankning fungerar nog bättre på professionella forum, i ett open source forum känns det som det är bättre om alla är jämlika och att man bara visar roller så att användare kan avgöra vem som är moderator/admin. Det motsäger dock inte att vi använder det man kallar för rank som en "Tack"-funktion istället.

**Comment by jonathan-dejong** [comment]
Jovisst, semantiken kan man ju diskutera :) 

Jag tror vi skulle behöva sätta upp en plan med målstolpar etc. för hur man ska gå vidare med hela projektet.

**Comment by EyesX** [comment]
Japp, det skulle vara bra. Jag har börjat på en med informationsstrukturen. Dvs. en wiki-post.

**Comment by EyesX** [comment]
Flyttar till 4.1 för att streamlina 4.0.

**Comment by PontusTideman** [comment]
https://wordpress.org/plugins/bbpress-like-button/ :+1:

**Comment by EyesX** [comment]
@th3gh0st tack. Fungerar bra. Vi fixar så att den använder Font Awesome som ikon så blir det perfekt.
