### ISSUE TITLE
[CSS]: Stilsättning för globala sökmallar

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#101]
Funktionaliteten för sökmallarna är klara. Jag har gett varje <article> klasser beroende på vilken innehållstyp innehållet kommer från.

Det som behöver göras är bl.a enhetliga rubriker, färgmarkering/ikoner beroende på innehållstyp för att lättare se var innehållet hör hemma och till sist lite putsning av uppdelning mellan resultaten.

**Comment by marcustisater** [comment]
Ok jag har lagt in lite grundläggande. Input?

Vi kanske kan skippa border och köra lite bättre färg byten beroende på vad det är för typ. Jag valde olika nyanser av den blåa färgen.

**Comment by EyesX** [comment]
Ja det måste nog var lite tydligare färgdifferenser på dom olika innehållstyperna. Börja med att bara köra olika färger på ikonerna. Jag skulle även plocka bort skuggningen på rubriker och göra som tunnare.

Bordern blir nog bättre 1px ljusgrå.

Sidan har fått sig en väldigt knepig formatering i headern också, något vi måste kolla på där.

**Comment by marcustisater** [comment]
sådär ja, bättre? fixade till huvudet också

**Comment by EyesX** [comment]
Nu börjar det likna något :+1: 

Man kanske skulle sänka storleken på datum ett steg och göra den lite ljusare.

**Comment by EyesX** [comment]
Lägga till en läs mer-knapp kan nog vara bra också.

**Comment by marcustisater** [comment]
nu är det inlagt.
