### ISSUE TITLE
[CSS]: Stilsättning för notifikationsdelen i profil

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#102]
Notifikationsdelen i profilen är relativt ny och behöver lite CSS-kärlek för att passa in lite bättre.

**Comment by marcustisater** [comment]
Jag har lagt in lite grundläggande stilsättning, det hade varit schyst om man kunde lägga in data-label i 
td för tbody så kan man visa de före varje tabellrad annars funderar jag bara på att vänsterställa eller göra om det responsivt eventullet bara visa title. Se slack :)

**Comment by marcustisater** [comment]
Har vi tid för detta eller ska jag göra någonting generellt istället? Vi kanske kan komplettera i 4.1

**Comment by EyesX** [comment]
Det får du avgöra om du hinner. önskvärt vore kanske att få det mer enhetligt med hur t.ex forumdelarna ser ut då det är ett snarlikt upplägg.

**Comment by marcustisater** [comment]
Vad tror du? Nöjd eller kanske ett färg byte?

**Comment by EyesX** [comment]
Generellt ok, det som ser lite märkligt ut nu är...

![noti_align](https://cloud.githubusercontent.com/assets/4299787/7952930/84e0f222-09bd-11e5-8b7a-e2b5f7deb48a.png)

**Comment by marcustisater** [comment]
Klart, jag lade till lite data attirbut också. nu blev det snyggt responsivt. Jag tog bort den blåa färgen och körde standard tyckte den tog för mycket plats.
