### ISSUE TITLE
[Forum/CSS]: Se över forumvyer för korrekt stilsättning

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#103]
Vissa vyer i forumet saknar stilsättning. Det handlar nog framför allt om att det kan saknar Bootstrap markup i olika vyer. 

Kolla över generellt så att vi har det enhetligt på alla forumsidor.

**Comment by marcustisater** [comment]
Det behövdes en bredd. Det fungerar bra nu på profilen, kan du dubbelkolla de vyer du har sett som är fel?

**Comment by EyesX** [comment]
http://dev.wpsv.se/grupper/oversattningar/forum/ padding ovanför forumtitel.

**Comment by EyesX** [comment]
http://dev.wpsv.se/members/wpsvse_admin/forums/ saknar fortfarande fullständig stilsättning för t.ex ramar, odd/even.

**Comment by marcustisater** [comment]
klart.
