### ISSUE TITLE
[CSS/BuddyPress]: Meddelandenotis vid sparande

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#106]
När man sparar gruppinställningar så visas ett meddelande om att gruppdetaljer har uppdaterats. Detta meddelande behöver nog en clearfix och kanske en stilsättning som stämmer överens med övriga notiser.

![sk__rmavbild_2015-06-02_kl _08 52 00](https://cloud.githubusercontent.com/assets/4299787/7941656/10985996-0959-11e5-9e7e-f88c61b9d84a.png)

**Comment by marcustisater** [comment]
Det behövs en clear: all vilket motsvarar en wrapper < div id="message-outer" >. Fixat för grupper kan vara bra att kolla andra uppdateringar också.
