### ISSUE TITLE
[CSS]: Justering för profilfält i profilindex

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#108]
Det behövs lite alignment för profilfälten på indexsidan för profiler.

**Comment by marcustisater** [comment]
Jag har ju lagt på grundläggande table stilsättning. Kan du kolla hur det blir när du har fyllt på med fält först innan jag kollar på finstilsättning. Nu ser det inte så bra ut

**Comment by EyesX** [comment]
Ser bra ut som grund. Testa att lägga till fler fält under Inställningar -> BuddyPress så får du mer innehåll att pilla runt med.

**Comment by marcustisater** [comment]
Stylat grundläggande nu.
