### ISSUE TITLE
Funktionalitet för global inloggning

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#11]
Eftersom vi hädanefter kommer att köra allt uteslutande i WordPress så behöver medlemspaneler skapas för att på ett bra sätt få med alla delar som berör medlemskap. Behöver inte vara något speciellt avancerat. Bara så att vi får med det i alla portaldelar på ett tydligt sätt.
- Gravatar
- Profillänk/Redigera profil
- Privata meddelanden
- Favoriter (bbPress)
- Grupper (BuddyPress)
- Ut-/Inloggning
- Registrering
- Återställning av lösenord

**Comment by jonathan-dejong** [comment]
Privata meddelanden är också en del av BuddyPress?

**Comment by EyesX** [comment]
Japp, det är nog en modul som tillkommit på senare tid i BP va?

**Comment by jonathan-dejong** [comment]
Tror det funnits ett tag iaf, även vid skapandet av ärendet. Men de är fan inte lätt att ha koll på allt!

**Comment by EyesX** [comment]
Se även #28

**Comment by EyesX** [comment]
![inlogg](https://cloud.githubusercontent.com/assets/4299787/7903951/cd79d61c-07eb-11e5-89cb-b26923d330b8.png)

Visas för användare som inte är inloggade. BuddyPress lägger vanligtvis bara till en länk och den visas dessutom inte alls i mobilvy. Här låter vi formuläret visas om man inte är inloggad i desktopvy och en inloggningsikon som länkar till inloggningssidan i mobilvy.

**Comment by EyesX** [comment]
Det som är kvar att göra här är att ta bort "Logga in"-länken som BP lägger till på vänster sida. Vi bör även kontrollera att en "Bli medlem"-länk kommer med när funktionen för registreringar är påslagen.
