### ISSUE TITLE
[CSS]: Högre break point för mobilmeny

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#117]
Logotypens bredd tillsammans med menyn gör att vi skulle behövas en högre break point för mobilmenyn för att inte skapa overlaps.

**Comment by marcustisater** [comment]
jag kollar på det

**Comment by marcustisater** [comment]
Jag har lagt in det för 991px då också layouten ändrades. Det kändes lämpligast.
