### ISSUE TITLE
[CSS/JS]Supposition

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#119]
Någonting som bör fixas till nästa release är dropdown menyerna. Om fönstret är för litet och menyn åker till höger bör den automatiskt byta håll till vänster istället. Det finns tillägg för detta säkert till Bootstrap som man kan kolla på.

**Comment by EyesX** [comment]
@marcustisater något du har möjlighet att kolla på de närmaste dagarna så att vi kan få med i 4.1?

**Comment by marcustisater** [comment]
Hmm, tyvärr inte. Jag har annat prioriterat som kommer i vägen.

Om du vill försöka dig på den här inför 4.1 så kan du kolla på [https://github.com/behigh/bootstrap_dropdowns_enhancement](https://github.com/behigh/bootstrap_dropdowns_enhancement) eller istället använda classen `pull-right` på sub menyerna så kanske det löser problemet.

**Comment by EyesX** [comment]
Fixat med:

```
@media handheld, only screen and (max-width:1499px) {
  .dropdown-menu {
    right: 0;
    left: auto;
  }
  .dropdown-submenu>.dropdown-menu {
    left: auto;
    right: 100%;
  }
}
```

**Comment by marcustisater** [comment]
Grymt. Enkel fix.
