### ISSUE TITLE
[CSS]: Aktivitetsflöde på startsidan för brett i mobilvy

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#122]
Aktivitetsflöde på startsidan är för brett i mobilvy, vilket skapar scroll i sidled. Den behövs nog "hårdare" regler för wrappern där.

**Comment by marcustisater** [comment]
Det hade med typsnittstorleken att göra för sektionsdelarna på startsidan. Det är fixat nu.
