### ISSUE TITLE
[CSS]: Hantering av gruppmedlemmar behöver stilsättning

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#126]
Hantering av gruppmedlemmar behöver stilsättning. Någon slags inramning vore bra här. Knapparna saknar också stilsättning och blir bara en rad med länkar.

**Comment by marcustisater** [comment]
lagt in lite stilsättning

**Comment by EyesX** [comment]
Blev bra, stänger denna.
