### ISSUE TITLE
[CSS]: Vänskapsknappar för medlemmar i grupper hamnar fel.

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#127]
Vänskapsknappar för medlemmar i grupper hamnar fel. Dom döljs bakom namn osv. Kan vara att det bara saknas en position:absolute eller liknande. Dessa knappar ska hamna i det övre högra hörnet.

**Comment by EyesX** [comment]
Dom hamnar nog fel på flera platser. Tror att vi har skapat lite CSS som krockar.

**Comment by marcustisater** [comment]
Det behövs justeras med if satsen annars ser det bra ut nu

**Comment by EyesX** [comment]
Bugg i BP, vi får justera lite css istället.
