### ISSUE TITLE
Webbhotellsjämförelse

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#128]
En av dom mest ställda frågorna både i forumet tidigare och i Facebook-gruppen, handlar om vilket webbhotell man ska välja.

Det får mig att tänka på att skapa en webbhotellsjämförelsesektion på portalen, där webbhotellen kan ange uppgifter och skicka in för vad man erbjuder i olika paket osv. Medlemmar kan ge omdömen och kommentera och detta ska vara helt opartiskt. Inga sponsrade placeringar eller liknande.

Diskutera gärna vidare och kom med idéer.

**Comment by EyesX** [comment]
Lite noteringar för vilken information som ska vara med, med fördel sådant som är intressant för installationer av WordPress.
- Webbhotellsnamn
- Adress
- Typ av tjänst (webbhotell/VPS/dedikerad server)
- Typ av kontrollpanel
- Utrymme
- Trafik/månad
- Antal domäner per konto
- Antal E-postkonton per konto
- MySQL
- PHP (versioner)
- Minne
- Backup
- Support
- Pris
- Övriga avgifter
- Villkor
- WP one-click-installation?

**Comment by marcustisater** [comment]
Bra punkter.

**Comment by marcustisater** [comment]
Jag funderar på en recensions lista på en sida där man kan filtrera bland olika webbhotell med en overall poäng som användare har gett på wpsv som sammanställs. Det skulle då kunna finna enskilda sidor för enskiljt webhotell där man kan läsa recensioner från användare som getts ut. Jag skulle kunna skissa ut något på balsamiq för att visa mitt tänk.

Ett annat förslag kan vara en enkel poll till att börja med.

**Comment by EyesX** [comment]
Ja, recensioner skulle egentligen kunna vara kommentarer till respektive webbhotell med omröstning. Lite så man har på WordPress.org.

Att varje webbhotell får en egen sida blir rätt naturligt om man skapar en anpassad posttyp.

**Comment by marcustisater** [comment]
Det låter som en bra början, ska försöka skissa ihop något de närmaste dagarna så kan vi justera det med din hjärna innan vi börja bygga på det :)

Absolut, en anpassad posttyp tänker jag också på. Vi kan köra med endast kommentarer och typ en 1/5 rating till det som man betygsätter med.

**Comment by marcustisater** [comment]
Du kan ju i för sig redan börja bygga på posttypen så kan jag kolla lite på hur vi kan lägga upp det med stilsättningen så man får ett bra UI/UX till det hela.

**Comment by EyesX** [comment]
Tror att det finns klara tillägg för att använda kommentarer som betygsättning. Dvs. det räknas ut ett medel osv.

Ja, skiss på :+1:

**Comment by marcustisater** [comment]
Super, försöker prioritera detta till nästa rel då. Det här verkar som ett roligt tillägg för sajten helt klart.

**Comment by marcustisater** [comment]
Är vi på samma tänk? Väldigt snabba prototypes, du förstår tänket.

Sitemap: https://cloud.githubusercontent.com/assets/2952332/9821705/3fee9054-58bc-11e5-8d94-c964211be59d.png)

Webhotell sida: https://cloud.githubusercontent.com/assets/2952332/9821715/4dbdce3e-58bc-11e5-954d-c938b45890a2.png

Listning (likt den som är standard på wpsv idag): https://cloud.githubusercontent.com/assets/2952332/9821716/4dbef610-58bc-11e5-8d97-2f026925ec60.png

**Comment by marcustisater** [comment]
https://cloud.githubusercontent.com/assets/2952332/9821715/4dbdce3e-58bc-11e5-954d-c938b45890a2.png

https://cloud.githubusercontent.com/assets/2952332/9821716/4dbef610-58bc-11e5-8d97-2f026925ec60.png

Jag är inte gjord för det här med design ;)

**Comment by marcustisater** [comment]
Jag tänker så här;

En listning för alla webhotell som finns inlagt likt medlems vyn
- En användare skall kunna filtrera för att lättare hitta 

Ett formulär för användare att lägga in webhotell (granskas av oss)
- En användare skall kunna skicka in förslag på hotell (inkl vissa fält och bild som vi granskar)

En sida för ett webhotell med all information och ett kommentarsfält)
- Fält  
- Kommentarer
- Eventuellt en WPSV rekommenderar klistermärke 

Vad tror du?

**Comment by EyesX** [comment]
Vi är helt på samma spår. Ser bra ut som första skiss!

För webbhotellens enskilda sidor skulle man kunna använda tabbat innehåll för att få med allt. Första tabben visar det mest väsentliga osv.

"WPSV rekommenderar", detta tror jag vi bör skippa. Ser gärna att detta blir helt opartiskt. Dvs. endast omdömen från användare och ren information.

**Comment by marcustisater** [comment]
Det låter bra, öppnar vi nytt repo för den innehållstypen?

**Comment by EyesX** [comment]
Fixat https://github.com/wpsvse/wpsvse-host-reviews
