### ISSUE TITLE
[BuddyPress]: Generell uppdatering av BP-mallar

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#129]
Flera av BuddyPress legacy-mallar har uppdaterats och skulle även behöva uppdateras för vårt tema. Det handlar mest om att applicera ajax på fler ställen och lite trimmade funktioner.

Man bör vara noga med att göra dessa ändringar utan att bryta nuvarande layout. Förbättringar är naturligtvis alltid välkomna.

**Comment by EyesX** [comment]
Uppdaterade ett stort antal legacy-mallar igår. Kollar igenom så att det inte har haft sönder någon layout. Det bör iaf tillföra viss förbättrad funktionalitet och bättre infogning av loopar.

**Comment by EyesX** [comment]
Nästa version av BuddyPress inkluderar omslagsbilder (likt Facebook) för profiler och grupper. Jag vet dock inte om det är något som vi vill använda. Jag gillar den rena looken vi har nu. Men vi kan ha i åtanke att detta i så fall kräver uppdatering av våra mallar för BuddyPress profiler och grupper.

**Comment by marcustisater** [comment]
Jag håller med, tycker vi kan avvakta med omslagsbilder nu.
