### ISSUE TITLE
[Admin]: Skapande av sektioner för utvecklare

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#140]
Jag tror att vi behöver se över hur vi kan skapa sektioner som bli mer tilltalande för utvecklare specifik. Detta t.ex en specifik forumsektion med underforum.

**Comment by marcustisater** [comment]
Vi kanske skulle behöva brainstorma här lite för det är kul om det kommer igång till nästa rel

**Comment by EyesX** [comment]
Absolut, all input är välkommen här.

**Comment by marcustisater** [comment]
Vi skippar det här för tillfället.
