### ISSUE TITLE
[CSS]: Bättre stacking för quick buttons

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#143]
Quick buttons som finns under headern behöver lite bättre stacking i vissa mindre mobilvyer där texter bryter rader, vilket gör att vissa texter hamnar under ikonen och andra inte.

**Comment by marcustisater** [comment]
Vilka quick buttons tänker du på? De fyra styckna som ligger under ser bra ut för mig eller tänker du på nerladdningsknapparna?

**Comment by EyesX** [comment]
Japp, det är dom fyra.

![quick-btns](https://cloud.githubusercontent.com/assets/4299787/10120376/18cb69c2-64b8-11e5-8c19-efe4e7e5c91a.png)

**Comment by marcustisater** [comment]
Mm, jag märkte det. Jag drog ner typsnitts storleken alternativet kan man göra cirklarna mindre.

**Comment by EyesX** [comment]
Det skulle kanske också fungera att lägga en clear på titeln och centrera i det läge som bilden ovan visar.

**Comment by marcustisater** [comment]
Hmm, ja det kanske är bättre. 

Jag märkte däremot att vissa desktop vyer också bryts.

**Comment by marcustisater** [comment]
Nu blev det bättre.

**Comment by marcustisater** [comment]
https://github.com/wpsvse/wpsvse/commit/3cf921a3a3e237258de6b465e4f8a824d707e69d

**Comment by EyesX** [comment]
:+1:
