### ISSUE TITLE
[CSS]: Twitter-widgeten har tappat sin padding

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#146]
Twitter-widgeten på startsidan verkar ha tappat sin padding till vänster efter den senaste uppdateringen.

**Comment by marcustisater** [comment]
Hmm intressant, det kan jag kolla på.

**Comment by EyesX** [comment]
Kan vara så att den nya stackingen jag fixade för grupperna på startsidan orsakar detta.
