### ISSUE TITLE
[Forum]: Tapatalk fungerar dåligt med bbPress

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#148]
Tyvärr kan jag inte ge Tapatalk några lovord alls efter att ha testa det lite mer under senare tid. Tapatalk var en riktigt bra forum-app, men det har gått märkbart utför.

Jag tror att vi vinner mer på att mobilanpassa forumet. Det kommer att kräva lite jobb, men blir nog i slutändan det bästa om användaren inte behöver använda en app och ska man gå vägen med en app så är det nog bättre att skapa en egen app.

Tanken med att göra forumet mobilanpassat är att köra mycket villkorsstyrd logik för vad som visas ju mindre enhet som används. Dvs. att det framför allt är det väsentliga som visas i mobilvyn. Detta kan kräva att vi gör en lite annan grundstacking för forumdelar.

Vi har gjort lite av detta på startsidan och bör kanske följa ungefär samma tänk i övriga forumet.

**Comment by marcustisater** [comment]
Jag kollar om man kan anpassa det mer i CSS.

**Comment by marcustisater** [comment]
Forum listning i mobil: https://cloud.githubusercontent.com/assets/2952332/10117313/c5911bcc-6452-11e5-961f-76ce2c1c1040.png

Ett forum inlägg i mobil: https://cloud.githubusercontent.com/assets/2952332/10117312/c57a9528-6452-11e5-8c6f-ed5e975087a0.png (kan vänsterställa profil också, snyggare..)

**Comment by EyesX** [comment]
Tycker det ser bra ut. Centrerat är nog det bästa.

**Comment by EyesX** [comment]
Ändringarna så långt ser riktigt bra ut. Vi behöver kolla över detta och se till så att det fungerar ok i mobila enheter, sen kan vi trimma det vart efter som. Plockar gärna bort Tapatalk så snart det är möjligt.

**Comment by EyesX** [comment]
Tapatalk har plockats bort helt.

Det kan tänkas att mindre anpassningar kan behövas för media queries. Låter denna issue vara öppen till vi har kollat igenom det fullt ut.

**Comment by EyesX** [comment]
Stänger denna till förmån för mer specifika issues för mobilanpassningar i forumdelar.
