### ISSUE TITLE
[Forum]: Stilsättning av listor i forumvyer

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#149]
I forumvyerna får listor endast delvis stilsättning. Det skulle behöva göras tydligare. Ex. http://wpsv.se/forum/amne/satta-upp-bbpress/#post-134353

**Comment by marcustisater** [comment]
Jag håller med.

**Comment by EyesX** [comment]
Man behöver ta med kodvisningen i beräkningen också eftersom dessa i vissa lägen använder listor.

**Comment by marcustisater** [comment]
Ja just det, kan försöka mig på den i alla fall ;)

**Comment by marcustisater** [comment]
Vi får prova runt lite, det här kanske duger för att kolla på inlägg. Jag är lite osäker hur anpassat det är att skriva ett svar.

**Comment by EyesX** [comment]
Ser ut att fungera korrekt i dev. Det behövs dock en padding-bottom. Fixar det.
