### ISSUE TITLE
[Gfx]: Ny logotyp

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#15]
Det vore trevligt att för en gång skull kanske gå ifrån den generiska WordPress-logotypen och skapa något mer unikt för WordPress Sverige utifrån den istället.

Alla förslag är välkomna.

Förslag på vad en logotyp bör innehålla:
- Någon slags grafisk symbol utifrån WordPress-logotypen
- Texten _WordPress Sverige_
- Slogan _Den officiella svenska portalen_
- Något som utstrålar Sverige (gul och blå?)

Alla förslag är dock välkomna, det kan vara kul att se vad för idéer som kan uppkomma.

**Comment by EyesX** [comment]
![logo-blue](https://f.cloud.github.com/assets/4299787/1466111/fa2145b8-456b-11e3-94e3-1742d64d3f38.png)

Om man vill göra det enkelt. Men vore trevligt med något lite mer unikt.

**Comment by EyesX** [comment]
Eftersom inga andra förslag har kommit så satte jag mig och kladda lite...

![wpsvse-skiss-logo-01-black](https://f.cloud.github.com/assets/4299787/1488869/a29f013c-4759-11e3-90e6-a79d3acf848b.png)

**Comment by EyesX** [comment]
En till i form av en textsymbol
![wpsvse-skiss-logo-09-black](https://f.cloud.github.com/assets/4299787/1498225/f2772372-4828-11e3-903e-589b931fb43f.png)

**Comment by EyesX** [comment]
Föregående koncept med text och färg
![wpsvse-skiss-logo-09-color](https://f.cloud.github.com/assets/4299787/1505934/edfe713e-48f9-11e3-8a2f-1d70fd4bfbc7.png)

**Comment by jonathan-dejong** [comment]
Jag ska se om jag kan sätta mig och skissa på något förslag på detta :) 

Jag gillar att du har gått ifrån den vanliga symbolen lite men tycker att readability på ovan är lite för dåligt..

**Comment by EyesX** [comment]
Det är lite av medvetet gjort, dvs. mer igenkännligt på bekostnad av readability. Mer av en symbol. Namnet är trots allt "WordPress Sverige".
