### ISSUE TITLE
BadgeOS - Något att fundera över

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#150]
Mattias kom med ett bra förslag att installera BadgeOS - https://wordpress.org/plugins/badgeos/. Det är någonting vi kan fundera på om vi kan få in det.

**Comment by EyesX** [comment]
Det skulle kunna vara en kul sporre. Det man skulle behöva kolla på är vad det skulle vara för typ av badges vi ska ge och vid vilka tillfällen. Det finns vissa, så som t.ex Översättare, Moderator, Utvecklare osv. som kan vara adminbestämda badges. Sen finns det standard så som efter X antal inlägg i forumet osv.

**Comment by marcustisater** [comment]
Absolut, jag kollade runt lite på dev verkar som man koppla det mot https://credly.com också och göra skräddarsydda ikoner. 

Jag tycker man kan börja som du har här;

**Admin bestämda badges:**
Översättare
Moderator
Utvecklare
Redaktör/Bloggare kanske?

**Uppnå** 
Det här är svårt. Vi ska nog inte ha för mycket då kan det lätt bli jobbigt. 

Förslag t.ex; 
Forum
-  Fått ett gillat inlägg
-  Kommenterat 50 gånger, 100 gånger, 200 gånger m.m
