### ISSUE TITLE
Gulp / Grunt

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#155]
Jag funderar på om det kan vara coolt att göra någonting med att lägga till gulp/grunt till projektet. Det skulle vara bra att kunna till exempel minimera och kombinera scripts och göra automatiserade uppgifter som att komprimera bilder, css förbättringar m.m. Det är rätt brett och om man lägger ner lite tid på det kan man få ett rätt snyggt workflow nackdelen kan vara att det tar tid och jobbigt för nya utvecklare att hänga på.

**Comment by EyesX** [comment]
Ja det är nog lite av en avvägning. Så långe vi tydligt kan visa för folk som kommer in hur det fungerar och vad dom eventuellt behöver tänka på så bör det mest kunna ses som en fördel.

Något att tänka på är att vi kanske behöver trimma upp den CSS som finns just nu. Få, lite bättre grundstruktur.

**Comment by marcustisater** [comment]
Ja så länge det är en fördel är det bra. CSS kan vara värt att styra upp tycker jag också, lite stökigt. Jag tänkte att man kan dela upp CSS i olika delar kanske använda postcss eller sass men det krävs lite mer jobb då och integrera det med gulp. 

Jag kan tänka över det och komma med något förslag så får vi se om du tycker det låter vettigt att använda annars kan jag kolla igenom CSS filen och indexera det bättre till en början.

**Comment by marcustisater** [comment]
påbörjat i branch gulp

**Comment by marcustisater** [comment]
Vi gör så här istället eftersom det är så pass tidsbrist och dåligt arrangemang från min sida.

Jag skippar grunt/gulp os.v och istället så rensar jag upp CSS/JS filerna så kan vi prata igenom att använda en task-runner vid senare tillfälle.
