### ISSUE TITLE
[CSS] Emojis infogat som bild

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#159]
Emojis använder ursprunglig bildstorlek när den används som en bild, något man kan kolla över så det sätts fasta regler för dessa också.

**Comment by EyesX** [comment]
Hmm, lurigt. Dom får ingen egen css-klass.

**Comment by EyesX** [comment]
Det är nog trots allt något som behöver ses över
http://wpsv.se/forum/amne/ta-bort-read-more-4/#post-134710

Redigera inte inlägget med den stora emojin, den får vara test case för nu.

**Comment by marcustisater** [comment]
Det verkar som ingen bild class läggs till. wp-smiley

**Comment by marcustisater** [comment]
Så här ser CSS ut för det

img.wp-smiley, img.emoji {
    width: 20px !important;
    height: 20px !important;
    max-height: 20px !important;
    vertical-align: middle !important;
}

**Comment by EyesX** [comment]
Nej precis, det är något skumt som händer där när emojin ska infogas.

**Comment by marcustisater** [comment]
Är det här fortfarande aktuellt?

**Comment by EyesX** [comment]
Inget som har märkts av, men samtidigt inte så många som använder text-smilies i sina inlägg.

**Comment by marcustisater** [comment]
Ok, inte så högt prioriterat då kanske.
