### ISSUE TITLE
[Gfx]: Ny grunddesign

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#16]
I och med uppdateringen av milestone 3.5, till 4.0, (se #14 ) så behöver vi en ny grund av design för version 4.0. Det med Bootstrap 3.0 och i stora drag ungefär samma upplägg som tidigare (det gäller väl framför allt startsidan).

Färgschemat är egentligen rätt öppet, men det kan vara trevligt att ha med utmärkande färger för WordPress, så som den WordPress-blå färgen.

**Comment by MartinL83** [comment]
Finns det skärmdumpar eller liknande från orginal siten? Har riktigt dålig koll på hur det hela såg ut förut.
Jag bidrar gärna med ideer, wireframes eller skisser i den utsträckningen jag kan och har tid (vilket tyvärr det är ganska dåligt om men ändå). Men som sagt dålig koll på hur det såg ut och vad som är tänkt.

Forum skall finnas, samt filarkiv (enbart språkfiler?). Buddypress, standardsetup i där folk kan umgås bara? Och jag förmodar nyheter och artiklar?

Ber redan nu om ursäkt ifall jag bara har missat info om det här någonstans =)

**Comment by EyesX** [comment]
Det gamla temat ligger som branch 3.0.

Ingenting måste se ut som det gjorde innan. Vi hade dock ett rätt bra upplägg på startsidan där vi fick med mycket information utan att det blev rörigt.

Här är en screenshot på den övre delen av startsidan
![wpsv se-officiella-valkommen](https://f.cloud.github.com/assets/4299787/1367107/535ee790-38fe-11e3-86c6-377c535a68a5.jpg)

Delen med flikar på startsidan
![flikar_wpsv](https://f.cloud.github.com/assets/4299787/1367106/534a9fb0-38fe-11e3-9a34-3b030bb85d08.png)

Sen fanns en tabell med senaste foruminläggen under det.

**Comment by MartinL83** [comment]
@EyesX Alright tack. 
Jag kan skissa lite på landningssidan med ungefär samma informationsstruktur ( dumt att ändra på något som funkar ) och laddar upp. Kanske det kommer lite mer ideer. Eller så kommer man underfull med vad som absolut inte fungerar.

**Comment by MartinL83** [comment]
Bifogar initial layout idee. Kan kanske sparka igång lite fler ideer om inte annat. Gult, blått och lite "berg" i bakgrunden i Jumbotronen för att försöka få det lite svenskt.

![wpse_ml_0001](https://f.cloud.github.com/assets/789633/1368027/8726b826-3978-11e3-9b3f-6902708fbfbb.jpg)

**Comment by EyesX** [comment]
Jag gillar känslan i följande Bootstrap-mall http://websites.simplesphere.net/flexland/files/index.html

Den skulle dock behöva lite anpassning så klart.

**Comment by MartinL83** [comment]
Alright, man skulle ju kunna lägga dom "Support, Forum, Filer, Dokumentation" nedanför i något tab liknande format med. Om man vill lyfta fram dom mer (?), och visa upp tex senaste support, forum aktivitet till höger vid klick. Och artiklar med nyheter nedanför.

Bifogar en söndags skiss.
![wpsv](https://f.cloud.github.com/assets/789633/1368896/3fea905a-39c7-11e3-999e-7233c7060989.jpg)

**Comment by EyesX** [comment]
Japp, eller så lägger man dom på rad som du hade gjort innan, men då med mallens stil (typ blåa ikoner mot vitt). Då får man inte så mycket att skrolla igenom. Vi bör gärna ha senaste ur forum, grupper, filer på startsidan också.

**Comment by andreasnrb** [comment]
Tycker nog @MartinL83 urspreungliga skiss var bättre. Kanske med kombon av mörkare nedladdningsomårde såsom var fallet i den andra skissen. Men det är egentligen sekundärt. kan alltid testa båda och se vilken folk gillar bäst.

**Comment by EyesX** [comment]
Vi har alla olika tycke och smak :) Det är bra om fler säger vad dom tycker.

Personligen tycker jag att @MartinL83 hittar känslan för konceptet med den första skissen, men den saknar lite den där levande känslan. Något av en sammanslagning mellan skissarna skulle nog passa.

**Comment by MartinL83** [comment]
Har inte hunnit arbeta mer på skisserna tyvärr. Men tänkte att det kan vara en idé och göra några snabba wireframes innan man fortsätter. Så alla är överens om informationsstrukturen i varje fall.

Bra med input på skisserna, bara att ösa på.

**Comment by jonathan-dejong** [comment]
Finns det möjlighet att nå PSD-filerna för det här så man kan fortsätta slipa? :)

**Comment by EyesX** [comment]
Jag har mallen jag länkade till. Kan slänga upp den på dropbox. @MartinL83 har kanske en PSD för sin skiss.

**Comment by EyesX** [comment]
Om ni vill ha tillgång till mallen jag länkade tidigare, droppa en e-postadress (Google-konto att föredra) så delar jag det med er via Google Drive. Vill inte lägga upp det här så vi stöter oss med någon licens.

**Comment by jonathan-dejong** [comment]
sure! jontedejong@gmail.com har jag för google drive :)

**Comment by MartinL83** [comment]
Jag kan dra upp psd filen ikväll eller i morgon på dagen.
Den 1 nov 2013 11:28 skrev "Jonathan de Jong" notifications@github.com:

**Comment by EyesX** [comment]
![wpsvse-take-1](https://f.cloud.github.com/assets/4299787/1521675/51945506-4b98-11e3-837c-2b5403e43641.png)

**Comment by jonathan-dejong** [comment]
Behöver något i den stora blå bakgrunden (har du säkert redan tänkt). Annars blir det bara som en stor wastead yta. Sen hade jag nog velat byta ut frågetecknet i support.. Vad är förresten support? Normalt brukar ju forum och support vara i princip synonymt på sådana här siter.. 

Finns det en tydlig formulering för var den här svenska portalens syfte ska vara? Ska den fungera som en svensk "ersättning" till wordpress.org i det att du kan gå hit för att få svensk support, svenska manualer etc. och sedan vidarelänkas till wordpress.org för themes/plugin/codex? Eller är det inriktat på att vara just ett community där folk kan diskutera WP, få hjälp etc. 

Förstår ju att det kan vara lite av varje men man kanske ska försöka pinpointa exakt vad folk mest vill ha ut/behöver ha ut av sidan och ge det en utmärkande roll i design och funktion.

**Comment by EyesX** [comment]
Jo precis, tanken är att man har ungefär den information som @MartinL83 har i sin skiss i den blå bakgrunden. Försökte också hitta något bättre än frågetecknet. Använde [Font Awesome](http://fontawesome.io/) för ikonerna.

"En svensk samlingsplats för WordPress-användare". Den största grundstenen har alltid varit forumet och det är framför allt support på svenska som har varit det som efterfrågats (lite av det vi ser i Facebook-gruppen just nu). Det har även varit en plattform för att förmedla svenska översättningar (för allt från WP till teman och tillägg).

"Support" på den gamla sidan tog besökaren till en sida där vi presenterade olika sätt att ta del av support, t.ex en supportmall, dokumentation, vanliga frågor, konceptet för community-driven support osv.

Tanken med en vidareutveckling är att försöka bygga ut funktionaliteten för att ge användarna möjligheten att översätta fler tillägg och teman tillsammans med hjälp av [GlotPress](http://blog.glotpress.org/). Med BuddyPress får vi även en tydligare möjlighet att skapa olika grupper inom communityn som kan tilldelas sina egna forumdelar (översättare, utvecklare osv.) och med det förhoppningsvis bredda portalen.

**Comment by MartinL83** [comment]
Hej, ursäkta svinsent svar. Men jobb och BF4 kom i vägen x)

Jag har dragit upp PSD filen på google Drive. Alla som önskar tillgång till denna droppa gärna era (g)mail adresser här.
@jonathan-dejong Har lagt till dig.

Ska försöka få lite mer tid här men en tanke som slog mig är. Vore det inte bättre att starta smått och sedan arbeta sig bredare med siten? Till exempel enbart satsa på att få upp Nyheter/artiklar samt forum i första rundan? Så att det hela inte ramlar på att projektet initialt blir för stort och ej färdigställs.
Detta kanske är planen, ursäkta om jag missat.

Samt. Sätta upp ett dokument / Wiki / Issue med struktur på vad som skall med och informations struktur? Så alla är på samma plan.

**Comment by EyesX** [comment]
@MartinL83 planen är nog helt enkelt att återskapa det vi hade innan (kanske skippa vissa delar som WP-Buzz (rss/twitter-agg)) och sedan låta dom nya funktioner vi får med på köpet i BuddyPress ha sin egen gång. Samma sak gäller väl egentligen GlotPress.

Jag kan skapa ett wiki-dok för lite informationsstruktur.

**Comment by EyesX** [comment]
Har börjat på ett dokument https://github.com/EyesX/wordpress-sverige-dev/wiki/Informationsstruktur-f%C3%B6r-projektet

**Comment by EyesX** [comment]
Jag fortsätter kladda lite med mallen...

![mockup-2014-01-05](https://f.cloud.github.com/assets/4299787/1847382/1c301e5a-7649-11e3-9ea6-9baa2ee058ae.PNG)

**Comment by EyesX** [comment]
Jag har fortsatt eftersom ingen sagt något annat ;) Vissa delar behöver fortfarande "fyllas på", men det blir en grund att jobba vidare med. En första liten känsla av hur forumet skulle kunna se ut får man med här också.

![wpsv_se-pre01](https://f.cloud.github.com/assets/4299787/2118817/de6005c2-9123-11e3-88cc-478655b37beb.png)
![wpsv_se-pre02](https://f.cloud.github.com/assets/4299787/2118809/a3ed0c46-9123-11e3-8199-51c09b0aa56e.png)
![wpsv_se-pre03](https://f.cloud.github.com/assets/4299787/2118808/a3eac238-9123-11e3-8095-c5fa67b0472c.png)
![wpsv_se-pre04](https://f.cloud.github.com/assets/4299787/2118812/a40afb98-9123-11e3-9854-0b81e3c85f5f.png)
![wpsv_se-pre05](https://f.cloud.github.com/assets/4299787/2118810/a409bc60-9123-11e3-814d-f47920b6fa40.png)
![wpsv_se-pre06](https://f.cloud.github.com/assets/4299787/2118811/a40a63fe-9123-11e3-8b30-6e4016975e5b.png)

**Comment by andreasnrb** [comment]
ser jäkligt snyggt ut

Den 9 februari 2014 01:49 skrev Mattias Tengblad notifications@github.com:

**Comment by jonathan-dejong** [comment]
Tycker också det ser schysst ut. Jag är inte helt såld på den blurriga bakgrunden då den känns väldigt random? Kanske går att få in något mer svenskt i bakgrunden men blurra det till någon slags balans mellan att man kan urskilja vad det är utan att det påverkar readability. 

Sen hade jag flyttat plats på sök i forum och skapa nytt (smådetaljer). Man vill ju helst att folk ska söka efter sitt problem först innan de gör en duplicate post ;)

**Comment by MartinL83** [comment]
Snyggt! 
Som @jonathan-dejong säger kanske man bör se till så att folk söker efter svar innan dom ställer en fråga. "Behöver du hjälp? [Sök efter svar här]". Eller något.

**Comment by EyesX** [comment]
Det kan nog vara en bra idé att byta plats på "sök" och "nytt inlägg" och lägga till lite text som uppmanar att man söker i första hand.

Jo bakgrunden är kanske lite random. Personligen tycker jag den bryter av rätt bra och skapar lite kontrast mot övriga delar. Men det är öppet att byta ut detta och som du säger, försöka ha något mer svenskt (har dock inte kommit på något bra).

**Comment by MartinL83** [comment]
@EyesX måste bara tillägga att jag tycker den nuvarande bakgrunden är jäkligt snygg. Menar inget annat =) Dock om någon kommer på något som har med Sverige att göra, så som @jonathan-dejong  sa är det ett plus.

**Comment by EyesX** [comment]
@MartinL83 är helt med på det :)

**Comment by EyesX** [comment]
Uppdatering av forumdelen efter förslag.

![wpsv_se-pre07](https://f.cloud.github.com/assets/4299787/2131231/948c3b3e-929d-11e3-82d9-ced11f24a9cb.png)

**Comment by EyesX** [comment]
Generell sida (i fullbredd)

![wpsv_se-pre08](https://f.cloud.github.com/assets/4299787/2133736/0946e1de-92cd-11e3-8e33-0d79e3c4dcc0.png)

**Comment by MartinL83** [comment]
En tanke slog mig angående bakgrundsbilden i header ( och liknande ). Man kanske kan ha något som liknar norrsken?

@EyesX looking good

**Comment by EyesX** [comment]
@MartinL83 ja det är ingen dum idé.

**Comment by EyesX** [comment]
Testade att använda en bakgrund med norrsken och barrskog. Ser rätt najs ut och känns lite mer "nordisk natthimmel". Dock ingen bild vi har några rättigheter till än. Var svårt att hitta bilder som inte hade för mycket av den typiskt gröna norrskensfärgen (den skär sig lite med övriga färgschema).

![wpsv_se-pre09](https://f.cloud.github.com/assets/4299787/2167742/89f342f4-9521-11e3-908d-48ad5772b9fc.png)

Design som HTML -> http://eyesx.me/html/wpsv.se/

Om vi känner att detta är en bra grund till en design så kanske vi kan stänga denna issue och skapa mer specifika issues för fortsatta element och design av specifika delar?

**Comment by EyesX** [comment]
Denna issue stängs. Skapa nya issues efter vad som behövs i designen så att vi lättare kan följa upp vad som är klart och inte.

http://eyesx.me/html/wpsv.se/
