### ISSUE TITLE
Disqus eller kommentarsfält?

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#163]
Jag har fått väldigt trevlig feedback från mitt blogginlägg via mejl och andra meddelande tyvärr inga kommentarer på själva inlägget. Jag börja fundera på om man skall använda de inbygga kommentarsfälten som finns i WordPress för att kanske får mer fart på det? Det känns också som ett generellt bättre sätt att få folk att registrera sig och mer aktivitet på aktivitetsflödet.

Det känns tyvärr lite segt att byta mitt under. 

Synpunkter?

**Comment by EyesX** [comment]
Jag är kluven. Till viss del kanske de inbyggda kommentarerna triggar aktivitet, men samtidigt triggar Disqus bättre uppföljningar. 

Samtidigt är det ju inget fel med att testa för att se vad som fungerar bäst. Vi behöver dock fixa mallarna för dom inbyggda kommentarerna först.

**Comment by marcustisater** [comment]
Japp, det finns både fördelar/nackdelar med de olika alternativ.

Ja mallarna måste fixas först, skulle också vara bra som en fallback.

**Comment by EyesX** [comment]
#54

**Comment by EyesX** [comment]
Stänger denna med hänvisning till #54
