### ISSUE TITLE
Optimering

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#166]
Hemsidan behöver optimeras för snabbare inladdnings tid.

**Comment by EyesX** [comment]
I och med detta bör vi även se över vilken cachelösning vi vill använda i form av tillägg.

**Comment by EyesX** [comment]
CSS-filerna behöver trimmas. Framför allt då sammanställa filerna för wp, buddypress och bbpress bättre och på så sätt kunna plocka bort sånt som är onödigt.

**Comment by marcustisater** [comment]
Absolut, jag har en license av WP-Rocket som vi skulle kunna testa med om du tror på det

Jag har en bra lösning för stylesheets & scripts kommer fungera. Jag funderar nästan på att skapa en ny branch för detta eller om jag gör allting i ett svep.

**Comment by EyesX** [comment]
Vad är det för typ av licens till WP-Rocket?

**Comment by marcustisater** [comment]
Det är GPL. Jag köpte personal http://wp-rocket.me/pricing/

**Comment by EyesX** [comment]
Ok, nackdelen där är att vi vill undvika löpande kostnader.

**Comment by marcustisater** [comment]
Hmm täcker inte den här life-time?

**Comment by marcustisater** [comment]
Vart ser du att det är löpande betalning?

**Comment by EyesX** [comment]
> 1 Year of Updates & Support**
> 
> **To continue to receive support and updates, all licenses must be renewed after one year (not compulsory).

**Comment by marcustisater** [comment]
se https://github.com/wpsvse/wpsvse-optimize-analysis - funderar på få det gjort till 4.1 lanseringen.

**Comment by marcustisater** [comment]
påbörjat i branch gulp.

Du får fundera på vilken bästa cachnings tillägg som är mest lämpligast, kanske W3?

**Comment by marcustisater** [comment]
Flyttar över till #181
