### ISSUE TITLE
[CSS]: Optimering av CSS-filer

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#167]
I och med #166 så behöver vi optimera, framför allt, 3 stora css-filer i style.css, buddypress.css och bbpress.css.

Det handlar om att:
- Plocka bort alla överflödiga regler (framför allt för bbPress och BuddyPress).
- Ordna upp så att css för respektive del ligger i respektive del
  - Generella CSS-regler i style.css
  - bbPress-regler i bbpress.css
  - BuddyPress-regler i buddypress.css
- Vissa regler kan slås ihop för bättre optimering

**Comment by EyesX** [comment]
- Plocka bort alla :focus för vanliga länkar och knappar (dess ser väldigt märkliga ut i vissa lägen).

**Comment by marcustisater** [comment]
Jag prioriterar detta i ett nytt branch, behöver kanske en halv dag för att städa upp allting.

**Comment by EyesX** [comment]
Hur ser tidsramen ut för detta?

**Comment by marcustisater** [comment]
Jag tänkte få det gjort idag.

**Comment by marcustisater** [comment]
Kort fråga kring `buddypress.css` och `bbpress.css`. Är det inte bäst att låta bli dessa med tanke på om de skulle uppdateras i framtiden och skriva över våra egna regler? 

Jag funderar ifall [https://github.com/giakki/uncss](https://github.com/giakki/uncss) skulle kunna vara något för att ta bort all överflödig css. Det känns som det kommer ta ett rätt bra tag att gå igenom allting manuellt.

**Comment by EyesX** [comment]
`buddypress.css` och `bbpress.css` är overrides för respektive system. De kommer alltså att laddas oavsett om de finns i temat eller inte.

**Comment by EyesX** [comment]
Aldrig testat uncss, beror lite på hur pass bra den kan göra det.

**Comment by marcustisater** [comment]
lyfter över denna till nya repot https://github.com/wpsvse/wpsv.se/issues/9
