### ISSUE TITLE
Konvertera DB, vBulletin -> bbPress

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#17]
Databasen för vBulletin behöver konverteras till bbPress. Den inbyggda konverteraren bör fungera. Vissa verkar ha haft problem med konverteraren, dock så verkar det vara på shared hosting, problem vi inte bör uppleva.

En sak man kanske bör tänka på när det kommer till användarnamn är att man inte kan använda mellanslag eller specialtecken. bbPress är alltså striktare när det kommer till användarnamn. Konverteraren ska hantera det genom att göra om "icke godkända" tecken och lägga till "-" för mellanslag. Det är kanske något vi kan se över och se om man kan utöka godkända tecken. Man kan dock alltid ändra visningsnamn i bbPress och på så sätt ändå visa sitt användarnamn som man vill ha det.

**Comment by EyesX** [comment]
En test-konvertering har genomförts utan problem. All data ser ut att komma med intakt.

**Comment by sarokse** [comment]
Tycker inte användarnamnet är något problem om det ändras. Borde man inte uppmana att istället använda e-postadress vid inloggning? Såg det fanns som plugin om det inte blivit tillgängligt som tillval i senare version av bbPress.

**Comment by EyesX** [comment]
Nej precis, det var min tanke också. Dvs. att man koncentrerar sig på e-postadressen istället. E-postadressen kommer kunna användas för att återställa sitt konto (något som måste göras iaf eftersom lösenorden nu är återställda). Vad man sen vill ha för visningsnamn kan man ändra i sin profil.

**Comment by sarokse** [comment]
Det tycker jag låter som en acceptabel lösning.

**_Om tid finns**_ inför lansering så skulle en snyggare lösning vara att automatiskt göra en återställning av lösenordet första gången de försöker logga in och sedan presentera information om varför. På det viset behöver man bara uppmana dem att logga in med e-postadress istället och på det viset tvinga ett lösenordsbyte. Det borde vara relativt snabbt att sätta en "flagga" på alla konton vid import som nollställs vid första inloggningen.

**Comment by EyesX** [comment]
Ja, det låter som bra idé om vi kan lösa det så.
