### ISSUE TITLE
Disquis för inlägg

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#171]
Alla inlägg verkar automatiskt få 1 kommentar inskrivet på startsidan. Vad kan det bero på?

**Comment by EyesX** [comment]
Detta är pingbacks som Disqus inte visar. Inget som egentligen är fel med andra ord. Det är fixat för dom inbyggda kommentarerna som vi slår på nu i veckan när 4.4 släpps :)

**Comment by marcustisater** [comment]
Japp, trodde så. Just det, på lördag.
