### ISSUE TITLE
Twitter-koppling och URL-förkortare.

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#178]
Vi behöver ändra så att Twitters t.co-förkortare inte används då denna är spammarkerad hos många ISPer osv. Helst bör ingen förkortning ske på våra redan förkortade adresser.

**Comment by EyesX** [comment]
Det verkar som om det är IFTTT som hämtar den förkortade versionen via Twitters API. Frågan är hur man undviker detta.

**Comment by EyesX** [comment]
Har nu stängt av "Auto shorten URLs" för IFTTT så får vi se om det hjälper.

**Comment by marcustisater** [comment]
Hmm, ja det kan nog vara det.

**Comment by EyesX** [comment]
Det hjälpte inte, det är Twitters API som tvingar t.co-förkortaren. Vi får kanske helt enkelt använda någon annan lösning för delning på Facebook.

**Comment by EyesX** [comment]
Jag har nu skapat en Facebook-app som används för att posta nyheterna och blogginlägg direkt på Facebook via tillägget Facebook Auto Post. 

Vi inväntar nästa inlägg. IFTTT-recepten har inaktiverats så länge.

**Comment by marcustisater** [comment]
Ok, låter bra.

**Comment by EyesX** [comment]
Facebook-appen är nu verifierad som fungerande.
