### ISSUE TITLE
Använda ett standard grundtema

### ISSUE THREAD

**Issue by andreasnrb** [wpsvse/wpsv.se-archived#18]
För att komma igång lite snabbare kan det ju vara bra att välja ett existerande grundtema. Finns ju en hel del att välja mellan. Dock är det lite snålt med teman med både bbPress och BuddyPress stöd. ThemeForest har ju en hel del men kvaliteten på dessa är inte de bästa. Iaf inte de jag kommit i kontakt med.

Några förslag
- http://underscores.me/
- http://my.studiopress.com/themes/ (har Genesis själv som jag kan "donera")
- http://themehybrid.com/hybrid-core

Tillägg @MartinL83 roots.io
- https://github.com/roots/roots http://roots.io/

**Comment by EyesX** [comment]
Det kan absolut vara en väg att gå. Att stödet inte finns handlar väl egentligen mest om att anpassa stilmallar för dessa sedan dom blev tillägg. Så det bör inte vara något som talar emot det.

Tack för erbjudande om att donera Genesis, det uppskattas!

Fler får gärna tycka till om vilken väg vi ska gå och vilket ramverk som kan göra sig bäst.

**Comment by sarokse** [comment]
Har nyligen gått över till Genesis, så om ramverk ska användas så får det min röst iallafall. I övrigt tycker jag många av de köpta temana från t.ex. Themeforest oftast är väldigt "kletiga" med en hel del onödig kod för att de ska fungera för så många fall som möjligt.

Hellre ett ramverk eller ett väldigt basic starter tema än ett fulländigt tema som anpassas.

**Comment by EyesX** [comment]
Instämmer, något "färdigt" tema är ingen bra variant. Ett ramverk, egen mall eller utifrån en mall är nog bästa vägen att gå. Speciellt med tanke på att vi kommer få ett relativt unikt upplägg för vissa delar.

**Comment by MartinL83** [comment]
Hej! Såg precis idag vad som har skett med wpsv.se. Tråkigt.

Ett förslag till grundtema att arbeta sig utifrån är "Roots". Har använt det på ett par projekt. Och sitter precis nu och jumpstartar ett projekt med WP+Buddypress+BBPress med Roots.
http://roots.io/

Baserat på HTML5 Boilerplate och Twitter Bootstrap.

**Comment by andreasnrb** [comment]
Roots kan ju användas också. Alla har tillgång till det och ingen utvecklare som blir kinkig för att man delar det publikt. Spanat på det men inte använt det själv.  Dokumentation, forum etc så nya utvecklare till wpse kan komma igång att leka med temat. Det kan vara siochså med enkelheten dock med composer, gruntjs och annat som kan behövas konfigureas. Jag kan ställa upp på att använda temat iaf.

**Comment by sarokse** [comment]
Testat roots vid några tillfällen längre tillbaka och en grej jag inte gillar med det är att de vill bygga in sitt egna tänk på bl.a. sökvägar (standard /wp-content/ och deras /assets/). Är väll kanske inte en avgörande faktor, mer en sån sak jag störde mig på av någon anledning. Kanske även är en sån sak man kan konfigurera upp efter tycke och smak.

I övrigt så är ju roots välanvänt och mina åsikter för roots är mer "tycke" än att de har någon direkt vettig grund att stå på så tänker inte vara den som säger nej till att använda det.

**Comment by MartinL83** [comment]
@cyonite Ja composer, gruntjs etc är en liten tröskel. Men det som jag tror kan ställa till med mest huvudbry är att dom använder en "theme wrapper" som om man ej har använt en, kan bli lite förvirrande (theme wrappern behövs ej användas dock).
http://roots.io/an-introduction-to-the-roots-theme-wrapper/
Dom använder sig även av LESS vilket jag personligen inte har bestämt mig för ifall jag gillar eller inte =) .. I vissa fall blir det mycket svårt att felsöka CSS.

@hantrick Ja det är ganska mycket special grejjer och tänk (se theme wrappern) i Roots. Det är dock väldigt enkelt att åsidosätta dessa. Tex för omskrivningen av wp-content till "assets" så behöver man bara ta bort en include fil.

Notera även att jag är ytterst dåligt insatt i vad som är tänkt / behövs till WPSE. Så jag är inte 100 på ifall Roots skulle passa. Man kan ju också använda det som grund och skala av. Så man slipper skräp man ej behöver.

Alternativt börja cleant och coppa in best of från andra teman. Med valfritt CSS ramverk som grund.

**Comment by EyesX** [comment]
Ska kolla in Roots också. Personligen gillar jag bootstrap så det kan nog gillas, men ska kolla in dom grejer ni nämner specifikt för Roots.

**Comment by andreasnrb** [comment]
Om Roots bedöms vara lite för komplicerat så är ju underscores av Automattic en tänkbar väg. Det är standalone dropin lösning och följer endast wp standard grejer så tröskeln är låg.

**Comment by EyesX** [comment]
Det finns lite aspekter att ta med när man ska avgöra vad vi börjar med. Dels så är det bra om vi använder en grund där vi är flera som känner sig klara med hur man jobbar med den. Flera ramverk kan ha en liten inlärningskurva och då kommer vi till nästa aspekt, tiden för utvecklingen är rätt avgörande. Vi bör komma igång med något relativt snabbt, utan att för det stressa fram något.

Vi har haft väldigt svårt att få med folk som deltar i utvecklingen av WordPress Sverige under 6 år och med den uppenbara risken att vi hamnar i samma situation igen så är det bra om vi lägger upp det så att folk lätt kan hoppa in och ta över där någon annan tidigare har utvecklat.

Eftersom sidan har rätt specifika behov så blir skillnaden mellan att använda ett ramverk, en färdig mall eller en ny mall baserat på t.ex Bootstrap marginell. 

Vi får helt enkelt inte måla in oss i ett hörn där saker blir mer avancerade än dom behöver vara i dagsläget.

**Comment by MartinL83** [comment]
Vill man använda Roots, men hålla det på en så pass simpel (och så nära "vanlig" Wordpress ) nivå som möjligt så kan det vara idee att skippa bygg script och theme wrappern.
Gör man det så har man i min mening en jäkligt bra grund. Men allt är smak och tycke. Och man bör arbeta med det man är van vid. Och som @EyesX säger, något som många klarar av att ta sig an om folk kommer och går.

@cyonite Har inte direkt testat underscores. Bara snabbt gluttat lite. Bra? Har för mig att det är riktigt sparsamt med kod, vilket är bra.

**Comment by andreasnrb** [comment]
@MartinL83 Det inkluderar endast det mest grundläggande som behövs för att göra ett tema. Inga specialgrejer alls. Ren WordPress bas som man ska ändra i och bygga vidare på. Så det är inget parent theme eller ramverk. 
Ni se koden här: https://github.com/automattic/_s

**Comment by EyesX** [comment]
Jag lägger nog min röst på just _s. Eller Genesis om vi ska använda ett ramverk.

**Comment by sarokse** [comment]
Efter läst era kommentarer och åsikter, så tycker jag nog underscores (_s) låter bäst för projektet. Hade gärna använt Genesis, men det ger både en högre inlärningskurva för nya utvecklare (mycket görs via hooks och actions) samt att det kan bli trassel med licenser om flera ska vara med och utveckla.

**Comment by EyesX** [comment]
Då kör vi på _s tycker jag. Har commitat det till repon.
