### ISSUE TITLE
Uppdaterad Twitter-widget

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#180]
Twitter har uppdaterat sin widget och med detta så blir widgeten på startsidan för Twitter alldeles för lång. Vi behöver uppdatera widgetkoden och/eller visa fler grupper.

**Comment by EyesX** [comment]
Kan vara idé att göra detta till ett widgetfält i WP också. Då anpassat till att visa vardera widget i fältet som flikar.

**Comment by marcustisater** [comment]
Ett litet "hack" förslag är att sätta en wrapper runt Twitter flödet och en max höjd med `overflow: auto`

**Comment by EyesX** [comment]
Tillfälligt löst med uppdaterad widgetkod. Vi skulle dock fortfarande behöva förbättra lösningen generellt.
