### ISSUE TITLE
Eventkalender

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#186]
Jag tror att en eventkalender skulle vara användbar. Dvs. en kalender där olika event kan läggas till av olika användare. Man kan lägga till meetups, WordCamps, onlineträffar osv.

**Comment by marcustisater** [comment]
Det skulle verkligen kunna vara någonting, hur är tanken att användare skall lägga till events? Via ett formulär eller är tanken att man också skall kunna lägga in privata händelser och för grupper?
