### ISSUE TITLE
Ny hemsida

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#188]
Halloj @khromov @EyesX @andersnoren @pelmered @bullpillaren med flera.

Från senaste uppstarts mötet så kom vi överens om att fortsätta med wpsv.se men att skala ner portalen. Vi behöver utveckla ett nytt tema med en ny WordPress installation men återanvända mycket av det som redan finns som design.

**Vad ska inte finnas med:**
* Forum
* Medlemmar
* Grupper 
* Översättnings portal

**Vad behövs?**
* Vanliga sidor som har bra tillgänglighet krav
* Formulär för att t.ex signa upp till vår Slack kanal.
* CPT - Blogg inlägg
* Nytt tema
* Ny WordPress installation
* Server byte till Servao.com, behöver fixas med domän här.

**Plan:**

1. Skapa en mockup där vi presenterar det nya flödet för vidareutveckling. Balsamiq? Annars vet jag att @andersnoren är väldigt duktig på design och kan säkert hitta på något till temat om han har tid/lust 😄 
2. Utveckla ett nytt tema men återanvända mycket av bilder/css från nuvarande. Ska vi t.ex använda ramverket Bootstrap på underscores? Jag tycker vi ska använda ny rolig och kanske utmanade teknik.
3. Innehåll - ska vi t.ex importera in blogg inlägg från wpsv.se nuvarande db. Här behövs det ett litet tema som tänker till kring det hela.

Jag tror det är bra att hålla allting väldigt simpelt fast med modern teknik och släppa en tidig version, sätta upp en rad med issues där utvecklare kan hjälpa till för vidareutveckling till sajten. Som sagt, för att göra det här roligt tror jag vi ska kolla på ny teknik och kanske hjälpa till med saker som man inte alltid är så van med att göra.

Vilka vill vara med? Svara gärna och lämna gärna någon åsikt kring denna plan. Jag tänkte agera som lite av en projekt ledare för det hela.

Jag kommer sätta upp ett nytt repo de närmaste dagarna med en radda av issues.

**Comment by khromov** [comment]
@marcustisater Bra sammanfattning.

En fundering: Behöver vi ett nytt tema på studs? Det gamla temat är ju snyggt och vi skulle väl kunna använda det rakt av? Så kan man börja lyfta diskussionen om ett nytt tema längre fram om det finns intresse.

**Comment by tobifjellner** [comment]
Behöver vi verkligen skapa ett nytt tema från grunden? Jag vet inte hur det tidigare såg ut, men numera är det viktigaste av allt att det ser bra ut och går att navigera från mobiler. Om inte det gamla temat klarar det, skulle jag föreslå ett dottertema till något av de senaste standardteman från ajto... Innehållet vi tänker oss på den nya sajten är ju inte alltför komplicerat.

**Comment by khromov** [comment]
En screenshot på gamla temat för de som inte sett det:

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343239393738372f323131383831372f64653630303563322d393132332d313165332d383863632d3437383635356233376265622e706e67](https://cloud.githubusercontent.com/assets/1207507/21067942/e2b8121a-be6e-11e6-9e97-a0527c7dde2c.png)

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343239393738372f323131383830382f61336561633233382d393132332d313165332d383039352d6335666136376230343732632e706e67](https://cloud.githubusercontent.com/assets/1207507/21068081/bd951374-be6f-11e6-8a08-671ab9b0676f.png)


Budskapet i headern bör definitivt ses över, men det är ett snyggt och enkelt responsivt tema.

**Comment by tobifjellner** [comment]
@khromov Vacker sida. Responsivt?

**Comment by khromov** [comment]
@tobifjellner Japp. Om jag minns rätt var @marcustisater med och tog fram det.

**Comment by tobifjellner** [comment]
Om vi fr.a. siktar på att visa vägen till olika resurser. Nedladdning kan ju t.ex. peka på sv.wordpress.org... så skulle en kul metafor vara vägvisningskyltar.
Något i stil med:
http://static.beta.pixgallery.com/images/detail/J/7/J/PIX-J7JUQL.jpg

**Comment by andersnoren** [comment]
Åtminstone delar av den gamla sajten finns bevarad med bilder och CSS på Archive.org, om man vill kika på gamla temat in action: https://web.archive.org/web/20150904200809/http://wpsv.se/

**Comment by marcustisater** [comment]
Helt rätt. Vi kör på det nuvarande temat och plockar bort delar som inte behövs så ser vi över det. Då kan vi nog få fram något rätt snabbt här så fort hosting är på plats. Jag ska prata med Otto.

Men jag tror temat behöver lite refacotiring se t.ex #181, #167, #176, #154

**Comment by marcustisater** [comment]
Jag börjar med att sätta upp temat och importerar bloggposter på nya servern så tar vi det därifrån.

**Comment by khromov** [comment]
Har vi SSH på Seravo? Jag funderar på om vi inte ska automatisera bygget, tex att när temat uppdateras i master så triggar det en automatisk release av temat i produktion. Vill även undersöka möjligheten att köra Composer för att installera WP och ev plugins.

**Comment by marcustisater** [comment]
Det finns tillgång till SSH, osäker om vi har root access. Jag ska höra med Otto.

**Comment by j-falk** [comment]
Dokumentation kring seravo t.ex. för ssh och composer finns på
https://seravo.com/docs/. Där finns också info om en vagrant miljö med
samma konfiguration som webbservern.

/Johan

**Comment by khromov** [comment]
Root behövs inte. Jag kikar på dokumentationen och återkommer med nytt ärende.

**Comment by pelmered** [comment]
Hur ska vi sköta arbetet med det här? 
Känns mest som det blir rörigt om man blandar in för mycket folk tidigt. Så länge vi kan hitta ett fåtal som kan dedikera lite tid till här så känns det smidigare.

@marcustisater: Hur mycket tid uppskattar du eller någon annan som har lite koll på kodbasen att det skulle ta att ta bort och städa upp nuvarande temat så att det fungerar? 
Ingen av de issues som nämndes ovan känns kritiska och sidan ser bra ut så det känns som vi kan köra på den gamla, åtminstone tills vidare.

**Comment by marcustisater** [comment]
Det fungerar men man behöver nog bryta loss lite delar om man ska ta bort forumet os.v. Jag skulle nog vilja göra om temat senare i temat men jag håller med - vi kör på detta nu.
