### ISSUE TITLE
Struktur på projektet, servern m.m

### ISSUE THREAD

**Issue by andreasnrb** [wpsvse/wpsv.se-archived#19]
(Kanske ska delas upp i fler issues men here goes)

Tycker vi ska använda wp-skeleton för sajtens struktur.
Frågan är ju sen om temat och andra delar ska ha egna repos och sen inkluderas mha moduler eller infogas direkt i sajtens repo.
## Huvudrepo för sajten
- använda wp-skeleton (https://github.com/markjaquith/WordPress-Skeleton)
- inkludera temat och plugins mha modul
- mindre wpse specifika plugins 
## Egna repo
- wpse-theme (kan vara av intresse för andra att lära ifrån leka med osv)
- eventuella 100% custom plugins
## Servern (om möjligt)
- nginx (med vagrant), använda sig av wp-stack http://wordpress.tv/2013/10/14/deploying-wordpress-with-wpstack/
- memcache/apc (anända w3 total cache)
- php 5.5
## Utveckling (för pluspoäng)
- wpse-vagrant som konfiguerar allt åt en för utveckling lokalt på datorn.

**Ändrar detta inlägg allteftersom beslut tas nedan**

**Comment by EyesX** [comment]
Nginx 1.4.3 och PHP 5.5.4 är redan fixat på servern. VI kommer även få lite backup på serversidan av FSdata.

Tanken med upplägget i repon när jag gjorde den var i princip att köra en "inside" wp-content. Jag vet inte om WP Stack kanske blir att ta i? Har själv inte använt wp-stack och misstänker att det är en liten inlärningskurva där?

**Comment by andreasnrb** [comment]
Jag tänkte att det kan vara bra att göra wpse så best practice som möjligt
så att projektet kan användas för de nya utvecklare etc som vill lära sig
strukturera lite större projekt, sajter osv.
Det kan vara att ta i med WP-stack, det kräver ju SSH access med capistrano
installerat, vet inte ifall FSdata ställer upp med sånt. Allt detta beror
ju på vilken nivå projektet ska ligga på.

Den 16 oktober 2013 15:09 skrev Mattias Tengblad notifications@github.com:

**Comment by EyesX** [comment]
Vi har en egen VPS så det ska inte vara några tekniska begränsningar på att ordna det.

**Comment by jonathan-dejong** [comment]
Jag tror det är lite en avvägning mellan best practice och enkelhet. Man vill samtidigt inte skrämma bort potentiella utvecklare pga. en learning curve som är onödigt hög.

Vagrant tycker jag är en bra idé, kör själv det på mina projekt.

**Comment by EyesX** [comment]
Jag har inte fått någon återkoppling av FSdata ang. assistans från deras sida så vi kan koncentrera oss på själva utveckling av sidan. (Är det dock någon som är sugen att hoppa på själv med detta så är det bara att säga till).

Som @jonathan-dejong nämner i #22 så vore det kanske bra att till en början iaf ha en hel avbild av en WP-installation i repon.

**Comment by EyesX** [comment]
Jag har gjort vissa uppdateringar för denna repo nu. Har bland annat skapat en organisation för WordPress Sverige så att det enskilt för ändamålet. Har även flyttat runt filerna lite och lagt till gitignore för WP så att det blir smidigare att forka.

**Comment by EyesX** [comment]
Nu ligger temat som en egen repo och som subtree under huvudrepon.
