### ISSUE TITLE
[Forum]: Rapportera inlägg/ämne

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#21]
Vi behöver ha någon slags funktionalitet för att kunna rapportera inlägg/ämnen till en moderator. Generellt så har vi haft globala moderatorer. Med bbPress+BuddyPress så kommer det dock komma med en del gruppforum som kanske är bra om dom modereras individuellt av gruppadmins.

Grundkonceptet är att moderatorer får en notifikation om någon väljer att rapportera ett inlägg/ämne för att snabbt kunna ta den åtgärd som ev. behövs. Det handlar alltså om att ge användare en länk/knapp där denna kan ange varför tråden rapporteras och sedan skicka det till moderatorerna via mail.

Man bör få det så att rapporteras något i allmänna forum så är det globala moderatorer som får rapporten och är det något som rapporteras i ett gruppforum så får även gruppadmin rapporten.

**Comment by EyesX** [comment]
http://wordpress.org/plugins/bbpress-report-content/

**Comment by ghost** [comment]
Jag har en Svensk översättning för det där tillägget (bbPress Report Content alltså).

**Comment by EyesX** [comment]
@keha76 super!

**Comment by ghost** [comment]
https://www.dropbox.com/s/6jyhp8i700rgbaa/bbpress-report-content-sv_SE.zip

**Comment by EyesX** [comment]
@keha76 tackar :+1:
