### ISSUE TITLE
Allmänna diskussioner, planering och tilldelning

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#22]
Startar en 'issue' för mer allmänna diskussioner och för att följa planering och tilldelning av projektet. På detta sätt kan vi hålla mer specifika issues rena från sådant som inte hör dit.
- [Informationsstruktur](https://github.com/EyesX/wordpress-sverige-dev/wiki/Informationsstruktur-f%C3%B6r-projektet)
- [Projektplanering, mål och delmål](https://github.com/EyesX/wordpress-sverige-dev/wiki/Projektplanering,-m%C3%A5l-och-delm%C3%A5l)

Vi skulle behöva få upp lite tempo och kanske tilldela specifika delar till olika personer. Alla behöver t.ex inte jobba med designen. Det finns möjlighet att redan nu börja skapa tillägg för dom delar som behöver det.

Feedback är naturligtvis alltid välkommen av alla i alla delar :)

**Comment by EyesX** [comment]
Jag har nu lagt till ett "due date" för att driva på lite och ge oss en deadline (inget skrivet i sten naturligtvis).

2014-01-16

**Comment by EyesX** [comment]
Deadline framflyttad 1 månad (2014-02-14) då vi inte sett någon aktivitet alls på senaste.

**Comment by EyesX** [comment]
Säg gärna till om det är något jag kan göra för att snabbare få projektet att gå framåt eller för göra det lättare att delta! Lite tråkigt om detta med helt öppen utveckling rinner ut i sanden. 

Saker vi skulle behöva få igång är t.ex följande:
- Färdigställa en grundmall att jobba mot, se #15 #16 
- Flera delar kommer att vara tillägg, här finns det möjlighet att redan nu börja bygga på dessa funktioner. Se #10 #21 #9 #7 #8 
- Ge feedback i issues (kan man göra även som icke programmeringskunnig)

**Comment by EyesX** [comment]
Jag har markerat grundmall #16 och logotyp #15 som klara. Många av dom element som är kvar att få in i temat är sådant som specifikt ska göras mot funktioner. Resterande ska fungera som en grund, speciellt om man använder Bootstrap3 markup.

**Comment by EyesX** [comment]
Intressant tillägg för användning till "Dokumentation", http://www.userpress.org 

Tidigare har tanken varit att använda WPMU Devs wiki, det är dock ett tillägg som använder årliga licenser (något vi så långt vi kan gärna undviker). UserPress ser dessutom ut att vara mycket mer streamlinat och har dessutom bättre grundfunktionalitet mot WPMUs variant. Det enda WPMUs variant egentligen har som fördel är wiki-upplägget som känns något mer standard.

Men UserPress helt klart mer tilltalade, inte minst som ett helt fritt alternativ. Vad tror ni?

**Comment by EyesX** [comment]
UserPress har blivit ett premiumalternativ med en rätt tilltagen årsavgift på $99 vilket gör att det inte är mycket till ett alternativ längre.

**Comment by jonathan-dejong** [comment]
Taskigt med userpress.. På vilket sätt ska vi använda dokumentation? Är tanken att det ska fungera som en svensk översättning av codex?

Angående  #15 #16 så är jag lite oklar på vilket tillvägagångssätt du använder för att koda detta? Skapar du hela designen som en statisk html först för att sedan applicera det på ett faktiskt WP tema? 

Överlag, vore det inte enklare att ha en hel WP installation (med gitignore standard för WP) i repot så vi kan jobba mot en lokal version och sedan pusha till branches / alt forkad lokal. ?

**Comment by EyesX** [comment]
@jonathan-dejong kanske inte som direkt översättning (finns på wp.org). Tidigare har det varit lite av dokument för att komma igång med WordPress och sånt som kommit upp som vanliga frågor. Men egentligen bör det inte ha någon direkt gräns för vad som kan skapas som dokument.

Lite så blir det, jag brukar skapa generella designelement i html och sedan applicera det som grund i ett wp-tema.

Ja det kan nog vara en bra grej. Vi kan ta det vidare i #19

**Comment by EyesX** [comment]
Jag koncentrerar mig på att få klart forum och generella mallar (t.ex för inlägg) för att man ska kunna öppna en bantad version relativt snart.

**Comment by EyesX** [comment]
@jonathan-dejong är #9 något som du skulle ha tid att kolla på? Försöker bolla fyrtioelva grejer och vill gärna få upp en bantad version av wpsvse snart. 

Vi har [stora delar](https://github.com/wpsvse/wpsv.se/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0+sort%3Aupdated-desc) av det som behövs för en tidig lansering klart.

**Comment by jonathan-dejong** [comment]
@EyesX  Jovisst det skulle jag nog.. Känns genomförbart :) Förstår att du har många bollar i luften! Jag har själv en flytt privat som börjar kännas genomförd (alltid något att fixa) och ett wp repo plugin som börjar ta sig. 

Jag ska se så att jag kan köra lokal utveckling av det här projektet. Var ett tag sedan nu så jag minns inte om jag fixade klart det. Då kan jag bygga tillägget klokt mot de vi har installerade.

**Comment by EyesX** [comment]
Kalas :+1: Då koncentrerar jag mig på att fixa klart mallar.

**Comment by EyesX** [comment]
För information. Jag kommer att skapa en hel del mindre issues närmaste tiden. Vissa kan ses som triviala, men det är mest får att få kolla på vad som är åtgärdat och inte så att man inte missar något.

**Comment by jonathan-dejong** [comment]
Jag har planerat att påbörja pluggen idag FYI :)

**Comment by EyesX** [comment]
:+1:

**Comment by jonathan-dejong** [comment]
Hur går jag bäst tillväga för att hålla en bra fork repo igång mot min egen utveckling? För pluginet tänkte jag köra en separat repo mot min fork med en upstream till originalet men för huvudrepot. Finns det något bättre sätt så jag kan synca mot samma mappar som jag arbetar mot lokalt (vagrant) eller är det dumt?

**Comment by jonathan-dejong** [comment]
Vore toppen att få tag på en "full" installation med DB som jag kan utgå ifrån när jag kodar.. så man har lite kött på benen ;)

**Comment by EyesX** [comment]
Huvudrepon består just nu av submoduler. För att hålla allt uppdaterat så är det bäst att köra alla subrepos enskilt forkade (gjort för att göra det så enkelt som möjligt även för den oinvigda).

Någon hel DB har vi inte i nuläget. 

Vi har dock en VPS som kan användas, den har dock ingen fullständig utvecklingsversion uppsatt.

Du får gärna komma med förslag på hur vi kan sätta upp dessa delar för att det dels ska bli så smidigt som möjligt att användas och dels inte har för hög inlärningströskel för den oinvigda som vill hjälpa till.

**Comment by EyesX** [comment]
Det finns nu Slack att tillgå för WordPress Sverige på https://wpsv.slack.com, efterfråga inbjudan via info at wpsv punkt se eller posta vilken e-postadress du vill ha inbjudan till i denna issue.

**Comment by j-falk** [comment]
Gärna tillgång till slack via johan@j-falk.se
Den 15 mar 2015 04:36 skrev "Mattias Tengblad" notifications@github.com:

**Comment by EyesX** [comment]
@jofa inbjudan skickad.

**Comment by jonathan-dejong** [comment]
jonathan@tigerton.se :) 

Använder redan slack sedan några månader och fan va gött det är..

**Comment by EyesX** [comment]
Denna issue stängs, alla hänvisas till slack :)
