### ISSUE TITLE
Funktionalitet för dokumentation

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#25]
Tidigare så har vi haft WPMU Wiki och UserPress i åtanke för dokumentationen. WPMU Wiki kan fortfarande vara ett alternativ då det är ett rätt billigt alternativ. Annars behöver vi skapa något eget och den svåra biten att alltid hålla uppdaterad där är öppen redigering av dokumenten.

Det är i funktionsväg annars en rätt basic wiki vi behöver. Dvs. dokumenthantering med öppna redigeringsmöjligheter.

**Comment by EyesX** [comment]
Flyttar till 4.1 för att streamlina 4.0.

**Comment by EyesX** [comment]
Kanske värt att kolla in https://github.com/boonebgorges/buddypress-docs

**Comment by EyesX** [comment]
BuddyPress Docs ser riktigt intressant ut. Att man dessutom kan associera det till olika grupper är suveränt för gruppspecifik dokumentation.

**Comment by EyesX** [comment]
Version 1.9 av BuddyPress Docs kommer att införa stöd för anpassade taxanomier och därmed passa perfekt för oss. Speciellt när dokument även kan integreras i grupper.

**Comment by EyesX** [comment]
Det går väldigt långsamt med uppdateringen av BuddyPress Docs. Vi kanske ska fundera på att bygga egen funktionalitet för detta och använda Formidable som front end editor. Vi tappar direktkopplingen till BuddyPress (men vi kan skapa liknande själva).

**Comment by marcustisater** [comment]
Det kan vara en bra idé att göra, ett mindre tillägg är väl altid positivt. Om vi hittar ett bra sätt att kunna göra någon slags koppling vore det bra.

**Comment by EyesX** [comment]
De flesta delarna för en första variant av vår dokumentation är klara. Två saker kvar att ordna med.

Första är att kolla varför vi får js-fel för tinymce och den nya länkdialogen när den används i front-end. Länkar är väsentliga.

`SCRIPT_DEBUG` är just nu påslaget i dev och ger felmeddelandet

> Uncaught TypeError: e is not a function tinymce.min.js?ver=4310-20160418:6

Detta fel är alltså något som uppstod i och med 4.5 och den uppdaterade länkdialogen. Vi behöver kolla ev. konflikter.

Det andra som är kvar att fixa är fördefinierade element i sidofältet. Det handlar om dokumentationsspecifik sök och knapp för att skapa nya artiklar i dokumentationen.

**Comment by EyesX** [comment]
Ser ut som Enlighter skapar problem med TinyMCE sedan 4.5. Vi kanske ska utnyttja GD bbPress Toolboxs shortcode för källkod fullt ut istället för att ladda det extremt tinymce-tunga Enlighter (laddar en massa extra i tinymce)?

Vi skulle behöva skapa ett eget plugin för TinyMCE så att vi får en enkel knapp i alla redigerare som använder WordPress visuella redigerare.
