### ISSUE TITLE
Anpassning av Adminbar

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#28]
Eftersom adminbaren används mer globalt med BuddyPress så kan det vara en bra idé att anpassa den för att bättre matcha övriga sidan.

Några saker att anpassa:
- Färganpassning
- Anpassad ikon (WP-ikon)
- Anpassade länkar för ikon
- Inloggningsform för icke inloggade användare

Detta är temaspecifikt och kan således byggas med temats functions.

**Comment by EyesX** [comment]
``` php
//**************************************************
// Brand Adminbar
//**************************************************
function wpsvse_brand_logo() {
    echo '
    <style type="text/css">
    #wpadminbar>#wp-toolbar #wp-admin-bar-wp-logo .ab-icon { 
        background-image: url(' . get_bloginfo('stylesheet_directory') . '/img/icons/brand-icon.png) !important; 
        background-position: 2px 5px;
        background-repeat: no-repeat;
        width: 22px;
    }
    #wpadminbar #wp-admin-bar-wp-logo>.ab-item .ab-icon:before {
        content: "";
    }
    #wpadminbar #wp-admin-bar-wp-logo.hover > .ab-item .ab-icon {
        background-position: 0 0;
    }   
    </style>
    ';
}

//hook into the administrative header output
add_action('wp_before_admin_bar_render', 'wpsvse_brand_logo');
```

Kan behöva justeras för en kanske högre adminbar efter anpassning.

**Comment by marcustisater** [comment]
Tack, jag kollar på det...

**Comment by EyesX** [comment]
Nu börjar den anpassade adminbaren ta form. Några småfixar behövs dock fortfarande. T.ex så behöver mobilvyn anpassning. Jag vet inte om man kanske även ska lägga lite mer padding på huvudmenyn (denna bli nog lite förminskad med den nya adminbaren).

**Comment by EyesX** [comment]
Jag har även lagt till 5 + 5 extra padding för navbar.

Det sista är att se över hur inloggning visas i adminbar, det kan tas i #11

**Comment by EyesX** [comment]
Ytterligare fix för att anpassningen ska se bra ut även i adminläget.
