### ISSUE TITLE
[CSS]: Se över responsiva delar av "Aktiva grupper"

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#37]
Sektionen "Aktiva grupper" på startsidan behöver ses över när det gäller responsiva delar.

**Comment by EyesX** [comment]
Detta handlar om att använda större bilder. Bildstorlekarna är satta i functions.php

**Comment by marcustisater** [comment]
Jag har börjat med att lägga in en max-bredd på 250px vid 500px breakpoint. Jag kollar av vid nästa deploy/push till produktions server.

**Comment by marcustisater** [comment]
Hmm det blir lite knas med plattorna när de går över, då lägger den sig på två rader. Det kanske räcker med en max-width och of hidden. Jag ska kolla på det.

**Comment by marcustisater** [comment]
Finally. Det var lite markup soppa som fixades.
