### ISSUE TITLE
[Forum]: Anpassning via bootstrap i mobilvy

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#39]
Vi kommer att använda TapaTalk för forum, men för visning i webbläsare så kan mobilvyn anpassas bättre genom att trigga olika media queries. Vissa kolumner kan t.ex bli överflödiga i mobilvy.

Generell anpassning via Bootstrap finns redan för forumvyerna (se #34 ).

**Comment by EyesX** [comment]
Lägg till en infobanner för forum om TapaTalk. Skala av forumdelar i mobilvy med bootstrap vilkorsstyrda css-regler.

**Comment by marcustisater** [comment]
Här behövs bara en info box om TapaTalk läggas in för jag har fixat full bredd på titel för forum vid mobil på startsidan. Det räcker med att lägga in classen alert alert-info för stilsättning.

**Comment by EyesX** [comment]
Det fixat jag.
