### ISSUE TITLE
[CSS]: Meny-highlight

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#44]
Se över så att alla delar for en korrekt meny-highlight. Det gäller framför allt undersidor för t.ex forum och BuddyPress-delar.

**Comment by marcustisater** [comment]
Kan du utveckla vad som ska göras här? Meny highlights menas med att när en meny länk är active? Det är redan stilsatt verkar det som.

**Comment by EyesX** [comment]
Detta är nog löst i och med att jag fixade en nav_walker. Stänger denna issue och skulle det saknas något så kan vi öppna den igen.
