### ISSUE TITLE
Enklaste sättet att få igång en lokal version av sidan?

### ISSUE THREAD

**Issue by j-falk** [wpsvse/wpsv.se-archived#46]
Hej

För en som inte är grym på git än, hur får jag upp en lokal version av sidan enklast? Ska jag klona wpsv.se och sedan även wpsvse i tema-mappen, eller räcker det med att klona wpsv.se? (är wpsvse inlänkat som en submodule?) Något annat man bör tänka på för att få upp en fungerande version lokalt?

Kanske en idé att sätta ihop en enkel steg-för-steg guide för sådana som mig som gör det enklare att komma igång?

**Comment by EyesX** [comment]
Jag körde en sub-tree på wpsv.se för wpsvse, det strulade något enormt, det blev istället att jag helt delade på dessa repos. Sen har vi inte haft någon aktivitet alls från andra så jag har bara pushat från min egen uppsättning. Mest pga att tilläggen skapade jag innan repon sattes upp och det har bara funnits behov för en specifik tema-repo.

Detta behöver absolut styras upp. Är dock osäker på vilket det bästa upplägget är?

Det mindre bra upplägget just nu:
**wpsv.se** - för tillägg och extra filer utanför tema (temat följer dock med :/ ) (här borde vi skapa en repo för tilläggen också).
**wpsvse** - för temat.

Det blir helt enkelt så att om man vill ha med allt så är det wpsv.se som gäller, men vill man pusha något så är det i dagsläget bäst att göra det mot wpsvse för temat och wpsv.se för andra filer.

Vi har pratat lite om detta i #19 men kom egentligen inte fram till något slutligt.

Jag ska försöka styra upp det nu under kvällen. Förslag på mest effektiva lösningen mottages gärna.

**Comment by j-falk** [comment]
Ok, det finns säkert personer som har mer erfarenhet kring hur man bör göra detta på bästa sätt men ska försöka ge min input.

Det finns ju en balans i detta mellan att använda best practice eller ett enklare tillvägagångssätt, något som kanske är  som ni också diskuterar i #19. Jag tycker det är en diskussion som även kommer upp i core kanalen i slack och jag kan tycka att det finns en poäng i att försöka hålla det enkelt för att underlätta för nya som vill lära sig och börja hjälpa till så gott de kan.

Därför kan jag tycka att det vore enklare om man kunde skippa att använda subtree för tyvärr är det nog t.o.m. ett hinder för en del att börja använda git (även om det är väl spenderad tid att sätta sig in i). Alternativet skulle annars kanske vara att sätta ihop en enkel guide så att t.o.m. sådana som jag kan komma igång.

Sedan tycker jag nog det vore schysst att ha de tilläggen som byggs specifikt för sajten som separata repos för att andra då enklare kan använda dessa tillägg till sina egna projekt om de vill och då även lättare kunna bidra med tillbaka med ev. förbättringar och buggfixar.

Sedan hur man knyter ihop det på ett schysst sätt vet jag inte. Om det blir som ett antal repos som man måste plocka in manuellt och om man seda kan använda någon dependency manger som typ composer i temat för att få ihop det snyggare. Det har jag tyvärr ingen egen erfarenhet av än, utan hittills har vi bara hanterat det manuellt själva.

**Comment by EyesX** [comment]
Ja det enklaste att komma igång med även för nybörjare är nog att helt enkelt bara dela upp specifika delar i egna repos (tema för sig och tilläggen för sig) och köra submodule på huvudrepon. Det blir kanske inte det mest effektiva men då kan man enkelt delta i utvecklingen av specifika delar. Det gäller dock att vi är tydliga vilka repos vi jobbar emot då så att vi inte förlorar något via submodule.

**Comment by EyesX** [comment]
Då ska vi se, nu har jag försökt att styra upp det lite tydligare.

Som referenserna här ovan visar så har alla delar nu delats upp i egna repos. Dessa plockas sedan in i huvudrepon med submoduler.

Jag har även skapat ett specifikt dokument för användning https://github.com/wpsvse/wpsv.se/wiki/Information-f%C3%B6r-GitHub-repos

Till sist så har jag även uppdaterat readme för wpsvse/wpsv.se för att spegla detta.

Hojta till om något är otydligt, allmänt knepigt eller inte fungerar :8ball:

**Comment by j-falk** [comment]
Underbart, tittar vidare på det i veckan.
Den 1 feb 2015 22:31 skrev "Mattias Tengblad" notifications@github.com:
