### ISSUE TITLE
Översättningar: bbPress, BuddyPress & tillägg

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#47]
Det är ett antal delar där vi behöver försäkra oss om att översättningar finns och är fullständiga. Vi kan i förstahand koncentrera oss på sådant som visas i front end. Det handlar framför allt om bbPress och BuddyPress.
### Projekt som behöver översättningar just nu:
- [bbPress](https://translate.wordpress.org/projects/bbpress/dev/sv/default) - 100% kontext kontrollerad. ~~Ett fåtal strängar som behöver översättas. Här krävs dock en hel del rättning. Det finns t.ex spår kvar från att man använt "tråd" istället för "ämne" som benämning.~~
- [BuddyPress](https://translate.wordpress.org/projects/buddypress/dev/sv/default) - 100% , en första kontextkontroll har gjorts. ~~Här är det lite fler strängar som behöver översättning. Man behöver även göra en helhetskontroll av kontext för strängar.~~
- ~~[Wiki Pro](http://premium.wpmudev.org/translate/projects/wiki) - (Kräver WPMU-konto) -  0% översatt~~
- [Download Monitor](https://github.com/download-monitor/download-monitor/tree/master/languages) - Är [helt översatt](https://github.com/EyesX/download-monitor/blob/master/languages/download-monitor-sv_SE.po) (jag har skapat en [pull request](https://github.com/download-monitor/download-monitor/pull/229) som inte är mergad än). Kontext av översättning kan behöva kontrolleras.
- [GD bbPress Tools](https://wordpress.org/plugins/gd-bbpress-tools/) - 100% översatt. ~~.pot-fil finns i nedladdningspaketet. (Säg till om du har en översättning eller om du börjar med denna översättning).~~
- [bbPress Like Button](https://wordpress.org/plugins/bbpress-like-button/) - 100% översatt. ~~.pot-fil finns i nedladdningspaketet. (Säg till om du har en översättning eller om du börjar med denna översättning). Detta är en låg-prio-översättning då alla strängar som visas i front end kan ändras i admin.~~

**Comment by EyesX** [comment]
BuddyPress 2.2 släpps inom kort. Det kan betyda att nya översättningsprojekt skapas på wordpress.org (det brukar dock dröja). För översikt av BuddyPress översättningsprojekt se https://translate.wordpress.org/projects/buddypress

**Comment by bpmildh** [comment]
Är det någon som är på bbPress-översättningen? Jag kan fixa den i helgen annars.

**Comment by EyesX** [comment]
@bpmildh den ligger på wp.org, så det är safe att köra även om någon annan också gör det.

Bara att köra på :+1:

**Comment by bpmildh** [comment]
Glotpress är rätt yxigt. Saknar sökning, rättstavning, översättningsminne osv. Finns det något sätt att använda Poedit och importera översättningen i stället, manualen var inte komplett på den punkten.

**Comment by EyesX** [comment]
@bpmildh ja det finns en hel del nackdelar med GlotPress. Dessvärre så undanbedes alla språkteam där det redan finns jobb gjort för översättningar att importera nya eftersom detta då ta bort erkännandet för dom som redan översatt. Det blir helt enkelt överskrivet av det som importeras :frowning: När det gäller just bbPress så är vi 3 personer som översatt, för mig personligen kvittar erkännandet, men jag vill inte köra över dom andra två.

**Comment by EyesX** [comment]
Jag har påbörjat GD bbPress Tools.

**Comment by EyesX** [comment]
bbPress Like Button är klart.

**Comment by EyesX** [comment]
BuddyPress - 100% , en första kontextkontroll har gjorts.

**Comment by EyesX** [comment]
Även bbPress fullständig.

Flyttar detta till milestone 4.1 då endast wiki kvarstår.
