### ISSUE TITLE
[BuddyPress/CSS]: Stilmallar för gruppvyer

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#53]
Stilmallar för gruppmedlemsvyn behöver uppdateras. Det är en av få delar som saknar förfinad struktur.

**Comment by marcustisater** [comment]
Det är bara att kolla igenom koden, osäker på vilka fält som ska visas så jag körde på title, grupp info och senast aktivitet.

**Comment by marcustisater** [comment]
Skulle du kunna kolla på sökrutan på gruppvyn? 

<?php bp_directory_groups_search_form(); ?>  behöver nog tweaks så den får bootstrap classerna annars får jag stilsätta om det inte går. Du har gjort liknade på front för forum-widget.

**Comment by EyesX** [comment]
La till ett filter för att ändra lite classer. Ajaxen som används är dock väldigt känslig för extra taggar, skulle med andra ord behövas liten css-fix för att göra formuläret enhetligt med t.ex forumsök.

**Comment by marcustisater** [comment]
Super, då fixar jag det sista.

**Comment by marcustisater** [comment]
Det ser bra ut som den är, jag fixade till input texten.
