### ISSUE TITLE
Använd inbyggda kommentarsmallar

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#54]
Återställ mallar för att använda WordPress standardmallar för kommentarer då vi kommer att använda Disqus för att hantera kommentarer.

**Comment by marcustisater** [comment]
Behövs någon extra stilsättning för disqus eller konfigurering av plugin? Jag antar att du lägger in det direkt på dev?

**Comment by EyesX** [comment]
Nej jag tror inte att det behövs. Disqus har bra generella stilmallar och passar bra som det är. Det är mindre administrativa inställningar som ska göras i Disqus admin, men det fixar jag i dev.

**Comment by marcustisater** [comment]
Stänger denna.

**Comment by EyesX** [comment]
Öppnar igen ;) Denna är för milestone 4.1. Ska man ha en fallback bör den ha någorlunda satta stilmallar. Men det är som sagt inget som behöver göras nu.

**Comment by EyesX** [comment]
Dom inbyggda mallarna kommer att se lite annorlunda ut gentemot innan. Kan vara bra att testa detta direkt i WordPress +4.4 med andra ord.

I övrigt kan vi kanske hålla liknande stil som vi har på aktivitetsflödet.

**Comment by EyesX** [comment]
Mallar skapade. CSS kvar.
