### ISSUE TITLE
[CSS]: Skapa generella stilmallar för widgets

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#55]
Det behöver skapas generella stilmallar för widgetfält så att inget faller ur ramen om nya typer av widgets ska läggas till.

**Comment by marcustisater** [comment]
Det är redan utplacerat med bootstrap grid så det behövs bara en word-break.

**Comment by EyesX** [comment]
Detta avser dock widgets för WordPress/bbPress/BuddyPress. Dvs. så att man får stilmallar för standardwidgets.

**Comment by marcustisater** [comment]
Jaha, då förstår jag!

**Comment by EyesX** [comment]
Här saknas det bland annat stilsättning för taggar (något som liknar labels här på github). Pilarna för listobjekt har hamnat ojämnt.

**Comment by EyesX** [comment]
Sätt en fast storlek på taggtexter. WordPress ger annars olika populära taggar olika storlekar.

**Comment by marcustisater** [comment]
japp, jag fixar det. Jag trodde det skulle kunna bli snyggt men när jag kollar på det nu ser det inte enhetligt ut.

**Comment by EyesX** [comment]
Kolla alignment på listobjekt i widgets.

**Comment by marcustisater** [comment]
Fast storlek på taggtexterna är nu inlagt. Hur menar du med alignement på listobjeketen, du menar marginalen? Den har jag minskat nu.

**Comment by EyesX** [comment]
Kolla hur pilarna ligger, ligger inte riktigt snyggt
