### ISSUE TITLE
[CSS]: Skapa anpassade mallar för JP Sharing

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#57]
Det är ingen mening att använda hela Jetpack, vi använder istället t.ex [JP Sharing](https://wordpress.org/plugins/jetpack-sharing/) som är delningsmodulen från Jetpack enskilt. Vi behöver dock skapa anpassade mallar för dessa delningsknappar. Dessa bör passa både för vanliga inlägg och forumvyer.

**Comment by marcustisater** [comment]
Jag har gjort lite grundläggande stilsättning för delningsknapparna men är det meningen att vi ska använda deras CSS stilsättning och skriva över annars kan vi eventuellt lägga in deras js till vårt tema och skriva helt egen css.

Inställningar för JPSharing bör vara (icons only) om min stilsättning ska fungera.

**Comment by EyesX** [comment]
Super, din första pull commitad :+1:
