### ISSUE TITLE
[CSS]: Stilmallar för sidindelning

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#58]
Stilmallar för sidindelning på inläggssidor behöver ses över. Här kommer vi att använda WP-PageNavi för förbättrad sidindelning. Det finns redan klara mallar för forum.

**Comment by marcustisater** [comment]
Har du satt upp WP-PageNavi ännu? Jag hittar inte...

Jag skulle behöva en ny db dump också.

**Comment by EyesX** [comment]
Bara att installera https://wordpress.org/plugins/wp-pagenavi/

Dumpen som ligger på slack är det som finns i dagsläget.

**Comment by marcustisater** [comment]
Sweet, tack.

**Comment by marcustisater** [comment]
Jag har lagt in stilsättning och lite templating, kolla av om det blev rätt. 
![wp-pagenavi](https://cloud.githubusercontent.com/assets/2952332/7215081/ecebd848-e5c6-11e4-83fe-98907a96a6a9.png)

**Comment by EyesX** [comment]
Ser bra ut, kanske köra med font-weight: normal?

**Comment by marcustisater** [comment]
Ja, jag kan ta bort det. Det blev lite för mycket... :)
