### ISSUE TITLE
[CSS]: Fel i forumvyn på startsidan.

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#60]
Inläggsräknaren i forumvyn på startsidan blir lite knepig och behöver en fix för när titeln går över 2 rader. Se bild.

![forumvy-startsidan](https://cloud.githubusercontent.com/assets/4299787/7410652/2c66d0ea-ef31-11e4-828a-f66e5d4e2f90.png)

**Comment by marcustisater** [comment]
Fixat, kommer i nästa merge.

**Comment by EyesX** [comment]
:+1:

**Comment by marcustisater** [comment]
Hmm fortfarande fel när den går över 2 rader. Jag får kolla igen på det.

**Comment by marcustisater** [comment]
behövdes vertical-align top så inte den absoluta postionering blir fel.
