### ISSUE TITLE
[Forum]: Akrivvy för forum behöver CSS-kärlek

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#61]
Akrivvy för forum får inte med all stilmallar. Se t.ex http://wpsv.se/forum/amnestagg/galleri/

Associerat #51

**Comment by marcustisater** [comment]
Det saknas ett id: `latest-forum` på wrappern vid row sen kommer allting rulla.

**Comment by marcustisater** [comment]
```
<section id="latest-forum" class="section"> 
```

**Comment by EyesX** [comment]
Ah, super.

**Comment by marcustisater** [comment]
Kan du fixa det? Hittar ej template.

**Comment by EyesX** [comment]
Yes, fixar.

**Comment by marcustisater** [comment]
Den här fixade väl sig när jag använde en annan selector eller hur var det...? Det verkar se bra ut nu. Vi glömde uppdatera denna issue eftersom vi tog det på slack.

**Comment by EyesX** [comment]
Denna var den som behövde en dubbel selector. Ser dock ut som jag redan fixat det, haha
