### ISSUE TITLE
[CSS]: Sidfot

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#63]
Vad ska finnas på sidfoten? När jag kollar på den statiska html så verkar det finnas någon sekundär meny och copyright sektion. Om du börjar lägga in sådant där så kan jag stilsätta det.

**Comment by marcustisater** [comment]
Se skillnad 
![skarmavbild 2015-05-01 kl 10 19 41](https://cloud.githubusercontent.com/assets/2952332/7428177/a8f4bf22-efeb-11e4-9c01-2427f6d86859.png)
![skarmavbild 2015-05-01 kl 10 19 27](https://cloud.githubusercontent.com/assets/2952332/7428178/a8f55bb2-efeb-11e4-8797-23aa02240a56.png)

**Comment by EyesX** [comment]
Det som blir där är att ingen meny är satt i admin för sidfoten, då faller den delen tillbaka på wp_list_pages. När en meny är aktiv så blir stilsättningen korrekt. Med andra ord kan det vara bra att helt enkelt bara skapa fallback css så att det ser korrekt ut i båda lägen. Borde inte behövas mycket mer än inline-block.

**Comment by marcustisater** [comment]
Jag fixade en fallback.
