### ISSUE TITLE
[CSS]: Stilmall för steg vid skapande av grupp

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#67]
Stegindikatorn vid skapande av nya grupper skulle behöva en bakgrund, förslagsvis grå som i andra liknande inline menyer.

![grupp-steg](https://cloud.githubusercontent.com/assets/4299787/7437845/cd09dc24-f05b-11e4-8c08-f436de642486.png)

**Comment by marcustisater** [comment]
Done
