### ISSUE TITLE
[CSS]: Stilmall för steg 4 i skapa grupp

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#68]
Steg 4, där man laddar upp en gruppbild, behöver lite allmän stilsättning. Se bild.

![grupp-steg4](https://cloud.githubusercontent.com/assets/4299787/7437894/4ca9be5e-f05c-11e4-98f8-9b4891b60b30.png)

**Comment by marcustisater** [comment]
Fixat, ändrade bilden i template så den är 256x256. Jag fixade även lite marginal emellan bilden och innehållet och sen lade jag till en line-height och padding fix på input file som fixade till så det ligger i mitten.

**Comment by EyesX** [comment]
Grymt!
