### ISSUE TITLE
Funktionalitet för filarkiv

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#7]
Det vettiga är nog att flytta ut funktionaliteten för filarkivet ur temat och istället göra det till ett tillägg.

Filarkivet bygger idag på anpassade posttyper och taxanomier tillsammans med Gravity Forms.

**Comment by EyesX** [comment]
Grundläggande funktionalitet för filarkiv:

Grundläggande funktionalitet:
- En anpassad posttyp för filarkiv
- Taxanomi för filkategorier
- Taxanomi för filtaggar
- Taxanomi för filversion
- Funktionalitet för att hantera filer som laddas upp/ner (kan till viss del skötas i Gravity Forms)
- Funktionalitet för filegenskaper, t.ex filstorlek, filtyp, osv.
- Funktionalitet för filbeskrivning, t.ex skapare, relaterade URLer, 
- Statistik för filer, antal nedladdningar, popularitet osv.
- Funktion för notifikationer vid uppladdning (kan kopplas mot t.ex Gravity Forms)
- Möjlighet för besökare att posta filer (kan kopplas mot t.ex Gravity Forms)
- Möjlighet för besökare att kommentera filuppladdningar

Låt det aktiva temat styra formateringen.

Äldre funktionalitet ligger under 3.0-grenen.

**Comment by EyesX** [comment]
Jag kollade på Download Monitor igen. Senast jag kollade så var det rätt omständligt skrivet och passade inte vårt ändamål riktigt. Det visar sig att Mike skrivit om tillägget från grunden och att det nu mer baseras på en egen posttyp. Det ser helt enkelt ut att passa våra ändamål perfekt nu mer. Mike är dessutom aktiv och en av dom mer seriösa tilläggsskaparna på wp.org.

https://github.com/mikejolley/download-monitor

Onödigt att uppfinna hjulet på nytt.

**Comment by jonathan-dejong** [comment]
Är detta tänkt typ som wordpress.org plugin repo?

**Comment by EyesX** [comment]
Kanske inte fullt så avancerat, Det är framför allt språkfiler som till en början kommer att husera som nedladdningar (vi har haft ett fåtal andra filer tidigare).

**Comment by EyesX** [comment]
Mallarna för Download Monitor behöver anpassas. Dessa grundmallar finns nu i temat under /wpsvse/download-monitor/

**Comment by EyesX** [comment]
Detta bör vi göra relativt enkelt för 4.0 och satsa lite mer på det till 4.1.

**Comment by EyesX** [comment]
Jag har gjort ett anta uppdateringar nu för nedladdningsmallarna. Det behövs nog dock lite mer stilsättning för att rama in det lite kanske?

![single-dl](https://cloud.githubusercontent.com/assets/4299787/8398804/bff64e12-1dfd-11e5-861f-028b9c03d36f.png)

**Comment by EyesX** [comment]
Nu börjar det bli klart. Det är bara kategorivisningen kvar och en do_shortcode på startsidans nedladdningar. 

http://dev.wpsv.se/filer/

**Comment by EyesX** [comment]
![downloads](https://cloud.githubusercontent.com/assets/4299787/8489450/c0c5452a-211b-11e5-8cf6-ba446979004b.png)

![single-dl02](https://cloud.githubusercontent.com/assets/4299787/8489455/c534202c-211b-11e5-97d8-bc8c644d8a53.png)

**Comment by EyesX** [comment]
Endast kategorivisning kvar.

**Comment by marcustisater** [comment]
Riktigt snyggt.

Glöm inte att byta plats på de bara, nu ligger Svenska över Internationell och di versa, mer enhetligt om de ligger staplade på varandra korrekt :+1:

**Comment by EyesX** [comment]
Du tänker på dom utvalda? Dom genereras dynamiskt. Olika sektioner så det bör inte vara något som gör något. Kommer att tillkomma fler kategorier osv.

**Comment by marcustisater** [comment]
Nej, jag tänker på de två blocken därefter WordPress (Internationell) och WordPress (Svenska), om de kan byta plats. Det känns användare vänligare...

**Comment by EyesX** [comment]
Kategorierna ordnas efter namn, så det går inte. Spelar mindre roll. Det är även en av anledningarna till att jag valde att lägga WordPress-nedladdningarna som utvalda.

**Comment by marcustisater** [comment]
Ahh ok, bra tänkt... 

Då förstår jag varför de låg så, blev lite förvirrad först.

**Comment by EyesX** [comment]
![single-dl-cat](https://cloud.githubusercontent.com/assets/4299787/8494727/dd7543ea-2167-11e5-9611-a2c80e0a1267.png)

**Comment by EyesX** [comment]
Ska bara kolla om det är något som behöver fixas för mobilvy, sen kan denna stängas.
