### ISSUE TITLE
[CSS]: Responsiva delar för snabbknappar

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#71]
Snabbknapparna under sidhuvudet på startsidan behöver ordnas för mobilvy.

Dom får lite ramar på fel ställen och det skulle inte skada om dom bli mindre i lägre upplösningar.

**Comment by marcustisater** [comment]
Blir detta bra? Kolla produktion. Jag fixade till sm och sen fick den en centering vid xs. Det blir lite dåligt med Community blocket eftersom det är så pass långt. Man kanske kan köra en word-break... hmmm

**Comment by EyesX** [comment]
Ser ut att ligga perfekt. Dock så har dom fortfarande borders som man kan dölja när dom stackas 100%

**Comment by marcustisater** [comment]
Sweet, border är fixad vid 100%
