### ISSUE TITLE
[CSS] Tooltip popup 

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#74]
Jag tycker tooltip ser lite konstig ut med den vita bakgrunden men det kanske finns en vits med det för kontrasten skull? Här kommer ett förslag annars hur vi skulle kunna stilsätta det. Kanske lägga på en border också eller box shadow. Vad tror du? Endast ett förslag... 
![today](https://cloud.githubusercontent.com/assets/2952332/7619491/6456376a-f9b9-11e4-8e2e-757e74a26858.png)
![new](https://cloud.githubusercontent.com/assets/2952332/7619490/64543384-f9b9-11e4-8ca4-3f385b98d642.png)

**Comment by EyesX** [comment]
Skulle låta den vara svart, blir kanske lite mycket blått. Men bakgrunden vet jag inte var den kommer från, den ska definitivt bort. Dvs. ditt förslag fast svart :)

**Comment by marcustisater** [comment]
jupp, svart blir nog bäst. Det var någon vit bakgrund. Jag lade en transparent bakgrund för att fixa till det.
