### ISSUE TITLE
[CSS] Medlemmar

### ISSUE THREAD

**Issue by marcustisater** [wpsvse/wpsv.se-archived#75]
Behöver medlems vyn stilsättas eller kommer vi använda den? Det skulle varit bra om vi fick alla länkar på huvudmeny klara så vi vet vilka vyer man kan skippa så att säga. 

se http://dev.wpsv.se/members/  (det finns dock färdiga för grupper så man kan använda de, behövs lite classer och andra konfigurationer som sökrutan m.m)

**Comment by EyesX** [comment]
Medlemsvyns kan komma att användas. Man skulle kanske dels grida upp den och lägga lite stilmallar på metadatan som visas för vardera användare. Även här skulle man kunna använda samma stil som gruppvyerna.

Ska försöka lägga till lite mer sidor i menyn så vi lättar ser. Generellt sätt så behöver det mesta dock vara någorlunda stilsatt.

**Comment by marcustisater** [comment]
Jag fixade till en gemensam class så det blir lättare att göra sådana här buddypress listor stilsättning i fortsättning, blir bättre dry också. Jag vet inte riktigt vilken meta data som ska med så lägger den standard. 

Jag gjorde om sökrutan som du hade gjort för gruppsökning. Kan du dubbelkolla om jag har gjort det rätt? Se https://github.com/wpsvse/wpsvse/commit/a59373bed78aeaf9ebb5c856b5081a2599ce1c79

**Comment by EyesX** [comment]
Ser korrekt ut.

**Comment by EyesX** [comment]
Det finns ytterligare metadata som behöver styling. Kan tänka mig att man får något liknande när man fått en förfrågan.

![member-req](https://cloud.githubusercontent.com/assets/4299787/7667840/26d9998c-fc1a-11e4-8a6c-c5436cd67d48.png)

**Comment by marcustisater** [comment]
Okej ett lite design dilemma. Om du kollar på hur det ser ut på front_page under aktiva grupper alla grupper som finns så kommer det oftast med en (gå med grupp/lämna grupp) knapp. Jämför med den på medlemsvyn. Vilken design ska vi köra på? Det känns lite fel att sätta olika knapp stilar, det har jag gjort med mening nu för att kolla vad du tycker.... :)

**Comment by marcustisater** [comment]
Jag stänger denna dock för det är klart. Öppna upp i ny ticket eller skriv på slack.

**Comment by EyesX** [comment]
En tanke, boxarna stackas ju snyggast om dom har en symmetrisk form, när knapparna för att lämna/gå med hamnar under så tar man bort lite av detta. Kanske skulle man istället använda Font Awesome och bara ha ett "+" för att gå med och ett "-" (minus) för att lämna? Då tar det minimalt med plats, är rätt tydligt ändå och man kan behålla formen på gruppboxarna.

**Comment by EyesX** [comment]
En tanke, boxarna stackas ju snyggast om dom har en symmetrisk form, när knapparna för att lämna/gå med hamnar under så tar man bort lite av detta. Kanske skulle man istället använda Font Awesome och bara ha ett "+" för att gå med och ett "-" (minus) för att lämna? Då tar det minimalt med plats, är rätt tydligt ändå och man kan behålla formen på gruppboxarna.

**Comment by EyesX** [comment]
http://fontawesome.io/icon/minus/

http://fontawesome.io/icon/plus/

**Comment by marcustisater** [comment]
Här skulle vi kunna lägga in .fa .fa-plus classen istället och ta gömma label i CSS. Det kan vara bra att behålla det för skärmläsningen. Jag kollar på det.

**Comment by EyesX** [comment]
Precis, det var min tanke också.

**Comment by marcustisater** [comment]
Hmm, tror du att du har en lucka för denna? Jag vet inte hur jag ska göra en generell funktion för detta ifrån buddypress. Jag får försöka sno någon annan ticket av dig för att komplettera ;)

**Comment by EyesX** [comment]
Jag kan kolla om jag kan fixa ett filter för detta.

**Comment by marcustisater** [comment]
Ok annars kan jag ful hacka det med CSS.

**Comment by EyesX** [comment]
I dagsläget ser det ut som ett fulhack i CSS är den smidigaste lösningen. Att använda filtret kommer troligen inte fungera tillfredsställande med AJAX. I BP codex föreslår man att använda språkfilerna för att göra denna typen av ändringar, vilket är en riktigt dålig idé eftersom språkfiler uppdateras automatiskt.

**Comment by marcustisater** [comment]
Super.

**Comment by EyesX** [comment]
Ytterligare medlemsvy som saknar bootstrap markup http://dev.wpsv.se/grupper/grupp-1/members/

**Comment by marcustisater** [comment]
Japp, jag löser det.

**Comment by EyesX** [comment]
Jag har missat att delen på startsidan trumfas av andra regler. Kollar det.

**Comment by EyesX** [comment]
Knappar klara, bara bootstrap markup kvar för gruppmedlemsvyn.

**Comment by marcustisater** [comment]
:+1:  grymt! då fixar jag resten ikväll/imorgon fm

**Comment by marcustisater** [comment]
Nu ska det vara klart.
