### ISSUE TITLE
[CSS]: Tvinga visning av submenyer i mobilyv

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#77]
Eftersom bootstrap är mobile first och egentligen inte har stöd för submenyner så behöver vi tvinga visningen av sub-sub-val i mobilvyn. Se #76

**Comment by marcustisater** [comment]
Kan du kolla på denna? den triggas på hover

**Comment by marcustisater** [comment]
Har du tid att kolla på denna? den triggas på hover...

**Comment by EyesX** [comment]
Funderar på hur vi ska göra med undervalen i huvudmenyn. Gillar inte att ha oncklick på menyer för desktop, det är dock väsentligt i touch-miljö. Något vi borde kunna lösa med lite JS.

**Comment by marcustisater** [comment]
Hover är fixat i desktop nu. Återstår supposition.

**Comment by marcustisater** [comment]
Nu är http://behigh.github.io/bootstrap_dropdowns_enhancement inlagt och fixat dock får jag inte tredje nivån att trigga i mobil korrekt. Den får inte open classen på listningen. Kan du ta en titt på det? Hover är däremot fixat sen kan vi också kolla på om vi vill försöka positionera ut communitys meny länkar till vänster istället så här http://behigh.github.io/bootstrap_dropdowns_enhancement/#positioning

**Comment by EyesX** [comment]
Kollar närmare på det.
