### ISSUE TITLE
[CSS/Forum]: Fältet för forumsignatur behöver styling

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#79]
Under profil -> redigera så saknar fältet för forumsignatur den korrekta stylingen. Detta fält kommer från tillägget GD bbPress Tools och behöver således specifika stilmallar satta.

**Comment by marcustisater** [comment]
Den saknar classen form-control. Hittat på flera ställen.

**Comment by EyesX** [comment]
Japp, därför behöver stylingen tvingas. Formuläret kommer som sagt från tillägget.

**Comment by marcustisater** [comment]
Jag har lagt en generell för buddypress. Se commit.
