### ISSUE TITLE
Funktionalitet för tracker

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#8]
Det vettiga är nog att flytta ut funktionaliteten för trackern ur temat och istället göra det till ett tillägg.

Trackern bygger idag på anpassade posttyper och taxanomier tillsammans med Gravity Forms.

Det saknas egentligen möjlighet till enkel hantering av trackern idag. Det är i stort standardfunktionalitet som används i WordPress. Något som också vore en fördel att få till.

**Comment by EyesX** [comment]
Det är alltså ett ärendesystem som behöver skapas som tillägg.

Grundläggande funktionalitet:
- En anpassad posttyp för ärendesystem
- Taxanomi för project
- Taxanomi för status
- Taxanomi för tilldelning
- Taxanomi för allvarlighetsgrad
- Funktion för notifikationer vid skapande/uppdatering av ärende
- Möjlighet för besökare att posta ärenden (kan kopplas mot t.ex Gravity Forms)
- Kommentarer för uppföljning/diskussioner

Tidigare använda funktioner finns att hitta under 3.0-grenen.

Vi bör tänka på att inte skapa några formateringar i tillägget utan låta temat sköta den biten.

**Comment by jonathan-dejong** [comment]
Definiera vad "trackern" är i det här sammanhanget? :)

**Comment by EyesX** [comment]
Enkelt sagt ett ärendesystem likt det som finns här på GitHub där man kan följa upp förslag på funktionalitet, buggar osv. för wpsv.se samt en del för att rapportera problem/fel i svenska språkfiler i dom olika projekten.

**Comment by EyesX** [comment]
Flyttar till 4.1 för att streamlina 4.0.

**Comment by EyesX** [comment]
Lägger denna på is. Behovet finns egentligen inte än.
