### ISSUE TITLE
[CSS]: Lägg till bakgrund för avatar/visningsbilder

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#82]
Det behövs nästan t.ex en ljusgrå bakgrund för avatarer och visningsbilder när vi har absoluta element satta på många av dessa. Man tappar annars linjerna i dessa listningar...

![ava-bg](https://cloud.githubusercontent.com/assets/4299787/7667876/d87574b6-fc1c-11e4-94ba-8606614e6a86.png)

![ava-bg2](https://cloud.githubusercontent.com/assets/4299787/7667878/ddb3507e-fc1c-11e4-8cde-8c0ecedf5978.png)

**Comment by EyesX** [comment]
https://github.com/wpsvse/wpsvse/commit/4216fc7

**Comment by marcustisater** [comment]
Jupp, håller med. I'm on it.

**Comment by marcustisater** [comment]
Fixat.
