### ISSUE TITLE
[CSS/JS]: Formulärkontroller visas felaktigt för statusuppdateringar

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#83]
Formulärkontrollerna för att göra statusuppdateringar visas felaktigt.

Aktiv
![form-ktrl](https://cloud.githubusercontent.com/assets/4299787/7667891/6db65a04-fc1d-11e4-866a-da72ee8de996.png)

Inaktiv efter fokus
![form-ktrl2](https://cloud.githubusercontent.com/assets/4299787/7667897/829e9ed6-fc1d-11e4-812b-f77633db75b2.png)

**Comment by marcustisater** [comment]
Blev det bättre nu? Kontrollera om du tycker höjden blev bra. Det låg i js.

**Comment by EyesX** [comment]
Perfekt! :+1: 

Stänger.
