### ISSUE TITLE
[GFX]: Favicon dammit!

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#86]
Vi måste ju ha en passande favicon! Ska se hur logotypen kan användas för det utan större anpassning.

**Comment by marcustisater** [comment]
Ja just det ja, haha. Det ska nog inte behövas någon större anpassning till det.

**Comment by EyesX** [comment]
Vi kan skapa en ny för apple och bokmärkesikoner i övriga storlekar. Det viktiga var faviconen.
