### ISSUE TITLE
[CSS]: Ramar för aktivitetsflödet kapas i mobilvy

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#89]
Ramarna för aktiviteter i aktivitetsflödet kapas i mobilvy. Gäller för både aktivitetsindex och startsidan.

![border-cut](https://cloud.githubusercontent.com/assets/4299787/7694721/78c6d298-fde4-11e4-8d24-b13aab734d39.png)

**Comment by marcustisater** [comment]
Done
