### ISSUE TITLE
[Forum]: Markera som löst

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#9]
bbPress har ingen funktionalitet för att ange ett ämne som löst. Detta är en betydande funktion i ett supportforum. Det är alltså något vi skulle behöva skapa ett tillägg för.
## Grundkonceptet för denna funktion:
- Den som har skapat ämnet eller forumledare/moderatorer ska kunna markera ett ämne som löst. Optimalt genom att i den enskilda ämnesvisningen markera svaret som är det som löst frågeställningen. Inlägget visas alltså med en formatering som gör att det sticker ut och t.ex ett titelprefix (kanske direktlänkat till lösningen). Andra som har liknande frågor kan med andra ord enkelt direkt hitta lösningen.
- Det ska även gå att avmarkera ett ämne/inlägg som löst. Man ska alltså kunna växla mellan löst/olöst.
- Vidare så markeras även ämnen i forumvyn med t.ex en ikon eller annat som indikerar att ämnet är löst.
- En fördel är även om ämnen kan filtreras baserat på om dessa är lösta eller inte.

**Comment by EyesX** [comment]
Jag brainstormar (med mig själv?). Man borde kunna göra det rätt enkelt och ange post meta för posttypen 'topic'. I ämnesvyn har man en knapp som visar "löst" respektive "olöst" beroende på vad som redan har angivits som post meta-värde. Vid klick uppdateras post meta med det värde som inte var satt innan (ajax api), det tillsammans med att man anger en specifik css-klass för ämnet om det är markerat som löst. Man behöver dock ha detta villkorsstyrt för att endast visas för författaren, moderatorer och administratörer.

Det blir relativt enkelt att skapa queries för löst/olösta ämnen med meta query och det kan visas visuellt om ett ämne är löst i olika forumvyer med specifika css-klasser.

Detta behöver skapas som ett tillägg/funktionstillägg.

Referenser:
http://codex.wordpress.org/Function_Reference/update_post_meta
http://codex.wordpress.org/AJAX_in_Plugins
http://hookr.io/functions/bbp_topic_class/

**Comment by j-falk** [comment]
Hej, jag är väl inte direkt någon utvecklare men kanske kan bidra lite mer kring koncept/lösning och kanske även lite kod om jag lyckas.

Funderade lite på om man skulle kunna titta runt lite på hur andra löst det? Har själv använt ett plugin Beaver Builder och deras supportforum en del. De har en dropdown som ägaren till inlägget och administratörer kan använda för att sätta status på inlägget. Tycker det sättet var ganska schysst.

![support for advanced custom fields 5 fields in widgets beaver builder](https://cloud.githubusercontent.com/assets/1665833/5992499/a814879a-aa2c-11e4-80f7-bf9692beceb7.png)

![beaver builder plugin beaver builder](https://cloud.githubusercontent.com/assets/1665833/5992506/d37c4d28-aa2c-11e4-8eb5-c55849de9495.png)

Att lägga detta som post meta känns ju som absolut som bästa lösningen och troligtvis så som de även löst det (men man skulle ju kunna fråga om man vill).

**Comment by j-falk** [comment]
Kanske i och för sig än mer logiskt att använda post status för detta? Så lägger man till en status som heter just löst (och så kan man döpa om publicerad till just olöst).

**Comment by EyesX** [comment]
@jofa det är ett koncept som jag har tittat på, ser ut att vara [Buddy-bbPress Support Topic](https://wordpress.org/plugins/buddy-bbpress-support-topic/) som används där. Det är ett tillägg som egentligen känns mer anpassat för customer support än den support som vi kommer att ha. Man måste t.ex ange om forumen ska kunna användas för support eller inte, vardera tråd har ursprungligen tre möjliga statusar (löst, inte löst, inte en supportfråga). Det känns som det blir ett lager för mycket när det kommer till statusar.

För oss skulle det som du är inne på räcka med en status, antingen är ämnet löst eller så är det bara ett vanligt ämne.

Personligen gillar jag inte att man sätter textattribut på titlar, tycker det förstör översikten i en forumvyn då man får hoppa i sidled för att läsa själva rubriken. Föredrar att man visar det mer rent visuellt.

Det enklaste konceptet jag kan komma på är att använda ett förinställt meta-värde för posttypen, då behöver man inte heller bråka med bbPress inbyggda statusar (klistrat, notis, stängt osv.)

**Comment by j-falk** [comment]
Ok, har inte jobbat med bbpress tidigare och låter logiskt att det kanske är enklast att hålla det som post meta då i så fall.

Förstår vad du menar med textattributen och håller med, kanske kan titta lite på hur github gör det med en ikon innan rubriken:

![issues wpsvse wpsv se](https://cloud.githubusercontent.com/assets/1665833/5993114/71447d4c-aa45-11e4-9c2b-04979b17334f.png)

Men känner att jag måste få koll på hur designen ser ut nu innan jag ger någon annan typ av feedback.

**Comment by EyesX** [comment]
@jofa precis min tanke med ikoner. Det är liknande det vi gjort med andra forumikoner (stängt, klistrad osv.) nu :+1:

**Comment by jonathan-dejong** [comment]
Repo för detta är non-existent: https://github.com/wpsvse/wpsvse-mark-solved

**Comment by EyesX** [comment]
Blev förfinat namn :P https://github.com/wpsvse/wpsvse-mark-resolved

**Comment by jonathan-dejong** [comment]
ah! ;) :+1:

**Comment by jonathan-dejong** [comment]
Bara en headsup på detta. Det är påbörjat men jag har dragit på mig lite sjukdom (klassiska vinter/vår grejen) så är lite efter i huvudet för tillfället :)

**Comment by marcustisater** [comment]
Vi tar bort forumet för tillfället.
