### ISSUE TITLE
[Forum]: Knapp för emojis

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#92]
Det skulle vara trevligt med en knapp för emoji i verktygsraden i redigeraren. Kolla om det finns några hooks eller liknande för detta i GD bbPress Toolbox.

**Comment by marcustisater** [comment]
Prova den du föreslog https://wordpress.org/plugins/tinymce-smiley-button/

**Comment by EyesX** [comment]
Detta ser intressant ut också https://wordpress.org/plugins/native-emoji/

**Comment by EyesX** [comment]
Detta bör läggas till i tillägget för forumredigeraren https://github.com/wpsvse/wpsvse-forum-editor

**Comment by marcustisater** [comment]
Vi tar bort forumet för tillfället.
