### ISSUE TITLE
[Forum/CSS]: Stilsättning för användarstatistik

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#94]
Delen med användarstatistik under användarens avatar och visningsnamn behöver formateras lite bättre. Det blir lite plottrigt där just nu. Förslagsvis lägger man lite margin-top på hela statistikblocket. Datumet för "Blev medlem" kan med fördel radbrytas.

**Comment by marcustisater** [comment]
Kommer ip numret att stå med?

**Comment by marcustisater** [comment]
Hmm, du får test köra den här lite nu. Vänta in nästa cron jobb bara tills den hämtar senaste.

**Comment by EyesX** [comment]
Tycker det ser bra ut. Funderar dock fortfarande på om användarnamnet inte blir aningen stort (ju färre längder användarnamn som tvingas till radbrytning desto bättre). Känns som 14px / bold räcker för att göra det framhävt.

**Comment by marcustisater** [comment]
Jag instämmer, fixar det.
