### ISSUE TITLE
[Forum/CSS]: Stilsättning för bilagor

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#95]
Kontrollera stilsättningen runt bilagor i forumet. Bl.a behöver rubriken för bilagor i inlägg bli mindre. Bilagorna vänsterställas utan mellanrum (bör gå i samma linje som innehållet). Se även över hur denna del ser ut i formuläret.

**Comment by marcustisater** [comment]
![skarmavbild 2015-05-27 kl 17 40 33](https://cloud.githubusercontent.com/assets/2952332/7840457/b6031612-0497-11e5-82ec-bc90a355a7d3.png)

**Comment by EyesX** [comment]
:+1:

**Comment by EyesX** [comment]
I formuläret skulle man kanske göra bilagsdelen i fullbredd och putta ner(?) adminlänkarna.

**Comment by marcustisater** [comment]
Jupp det kan man göra, jag trodde det låg i en annan ticket. Jag kollar. Se slack också angående gdpress.

**Comment by marcustisater** [comment]
Fixat!
