### ISSUE TITLE
Lightbox för bilder

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#97]
Vi skulle behöva någon form av lightbox för bilder. Inte minst för sådant som bifogas i forumet. Men det är nog bra att ha en generellt.

**Comment by marcustisater** [comment]
http://www.frescojs.com/ är väldigt bra annars finns http://photoswipe.com/ som är väldigt hipp

**Comment by EyesX** [comment]
http://fancyapps.com/fancybox/ finns också

**Comment by marcustisater** [comment]
Den verkar också bra. Support för touch swipe?

**Comment by EyesX** [comment]
Vet inte, tror inte det.

**Comment by marcustisater** [comment]
Ok ingeting livsnödviktigt. Ta det biblioteket som går snabbast att implementera så kan man byta senare vid kanske 4.1 om det inte skulle vara någon vidare.

**Comment by EyesX** [comment]
Kör på Magnific Popup http://dimsemenov.com/plugins/magnific-popup/

Triggas med selector .lightbox
