### ISSUE TITLE
[Forum]: Syntax highlight

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#98]
Någon form av syntax highlight, inte minst för forumet skulle vara bra. Blir alltid lättare att få översikt med en sådan.

bbPress framhäver gärna [Crayon Syntax Highligheter](https://wordpress.org/plugins/crayon-syntax-highlighter/), det har dessutom inbyggt stöd för bbPress. Men det finns kanske andra förslag?

**Comment by marcustisater** [comment]
Jag gillar Craynon men det kommer med många olika teman vilket vi kanske inte kommer att använda.

**Comment by EyesX** [comment]
Flyttar denna till 4.0.1. GD bbPress Toolbox egna bbkod är lite yxig i vissa delar och vi kanske behöver fundera på att gå över till TinyMCE som redigerare istället (den känner dom flesta användarna igen också).

**Comment by EyesX** [comment]
Har suttit och testat Crayon på dev med framgång. Av någon anledning så går det dock inte att aktivera det på prod. Något verkar krocka, men inga felloggar över felet skapa alls. Det verkar dock vara en bugg i Crayon som skapar "fatal error" vid aktivering (flera användare som rapporterat detta). Vanligtvis slänger dessa fel ut meddelande i samband med felet, det sker dock inte med Crayon och utan att få någon fingervisning om var det tar stopp så känns det rätt lönlöst att felsöka det.

Ett alternativ till tillägg är "Enlighter - Customizable Syntax Highlighter". Kör lite tester med det just nu för att se om det kan något att köra live.

**Comment by EyesX** [comment]
En bugg uppstår när kod ska infogas med nuvarande lösning med Enlighter och bbkod-redigeraren från GD bbPress Toolbox. Markerar man en kodsträng och klickar på knappen för kod så infogas [pre]-taggarna, men alla ev. "(" och ")" ersätts av "[" respektive "]", vilket blir felaktigt kod. Det lutar allt mer åt att TinyMCE är det bättre lösningen som redigerare.

Ref: #131

**Comment by EyesX** [comment]
Ytterligare ett problem som dyker upp. Enkla ' fnuttar blir omgjorda till citationstecken `

**Comment by EyesX** [comment]
Detta ska nu vara åtgärdat med det nya tillägget för att använda TinyMCE.

Jag har testkört med både rollerna "Deltagare" och "Administratör".
